/** Burke product libraries (client-safe). Import from `@/lib/burke`. Server code: `@/lib/burke/server`. */

export {
  ADDRESS_FIELD_MIN_QUERY_LENGTH,
  ADDRESS_STATUS_DISPLAY_ORDER,
  ADDRESS_STATUS_SECTION_LABELS,
  BURKE_GEOCODE_BATCH_API_PATH,
  BURKE_GEOCODE_BATCH_MAX,
  BURKE_GEOCODE_BATCH_RETRY_MS,
  BURKE_GEOCODE_CLIENT_BATCH_SIZE,
  BURKE_GEOCODE_LOOKUP_COALESCE_MS,
  BURKE_GEOCODE_QUERY_PARAM,
  GOOGLE_GEOCODE_API_URL,
  GOOGLE_GEOCODE_BATCH_CONCURRENCY,
  applyGeocodeResponseToRow,
  applyGeocodeWithTargetContext,
  addressFieldValuesEqual,
  clearGeocodeCache,
  countAddressStatuses,
  deriveAddressFieldStatus,
  effectiveAddressFieldStatus,
  emptyAddressFieldValue,
  groupSecondaryRowsByEffectiveStatus,
  isAddressResolved,
  isLookupSettledForRow,
  normalizeGeocodeQuery,
  parseRegionHintFromFormatted,
  queryLikelyNeedsRegionContext,
  sanitizeGeocodeResponse,
  withRegionContext,
  shouldEmitAddressFieldStatusChange,
} from "./geo";
export type {
  AddressFieldStatus,
  AddressFieldValue,
  AddressStatusDisplayKey,
  GeocodeResponse,
  GeocodeSuggestion,
} from "./geo";
export {
  BURKE_LOCATION_FINDER_ACCESS_PATH,
  BURKE_LOCATION_FINDER_GRANT_COOKIE,
  BURKE_PROXIMITY_API_PATH,
  BURKE_REVOKE_LOCATION_FINDER_ACCESS_PATH,
  BURKE_VERIFY_LOCATION_FINDER_PASSWORD_PATH,
  INITIAL_SECONDARY_ROW_ID,
  LOCATION_FINDER_MAX_SECONDARY_LOCATIONS,
  LOCATION_FINDER_FOOTER_CLEAR_CONFIRM,
  dedupeResolvedLocations,
  expandProximityMatches,
  expandProximityRoutingDiagnostics,
  LOCATION_FINDER_GEOCODE_RESPONSES_KEY,
  LOCATION_FINDER_STORAGE_TTL_MS,
  LOCATION_FINDER_TOOL_ID,
  clearLocationFinderStoredData,
  exportLocationFinderCacheDownloadBody,
  buildProximityRoutingDiagnostics,
  filterByMilesThreshold,
  filterByDrivingMilesThreshold,
  formatRequestRoutingFailure,
  hasDrivingRoutingIssues,
  listProximityMetricsMiles,
  listProximityMetricsDriving,
  normalizeDistanceUnit,
  isDrivingDistanceUnit,
  isStraightLineDistanceUnit,
  isWithinMapDisplayCap,
  MAP_MAX_PROXIMITY_PERCENT,
  markerTierForDistance,
  markerTierFromProximityPercent,
  markerTierLegendLabel,
  MARKER_TIER_MAX_PERCENT,
  proximityPercent,
  findStoredGeocodeResponse,
  findStoredProximityDrivingDiagnostics,
  findStoredProximityMatches,
  findStoredProximityMetrics,
  getLocationFinderStorageServerSnapshot,
  getLocationFinderStorageSnapshot,
  isValidThreshold,
  mergeFormDraftIntoLocationFinderData,
  mergeGeocodeResponseIntoLocationFinderData,
  mergeProximityMatchesIntoLocationFinderData,
  nextSecondaryRowId,
  parseLocationFinderStorageRaw,
  parseLocationsCsv,
  readGeocodeResponseMap,
  readLocationFinderFormDraft,
  subscribeLocationFinderStorage,
  writeLocationFinderStoredData,
} from "./location-finder";
export type { ProximityMarkerTier } from "./location-finder";
export type {
  DistanceThreshold,
  DistanceUnit,
  LocationFinderFormDraft,
  LocationFinderStoredData,
  ProximityMatch,
  ProximityRoutingDiagnostics,
  ResolvedLocation,
  RoutingLegFailureCode,
  RoutingRootCauseReport,
  StoredSecondaryRow,
  UnroutedLegSummary,
} from "./location-finder";
export {
  OFF_ROAD_SNAP_METERS,
  routingLegFailureHint,
  routingLegFailureMessage,
} from "./location-finder";
export { BURKE_HOME_PATH, BURKE_LOCATION_FINDER_PATH } from "./paths";
