import { FORM_IDS, GAME_IDS } from "./constants";
import type { FormId, GameId } from "./constants";
import { MOVES } from "./moves";
import type { MoveId } from "./moves";
import { TYPES } from "./types";
import type { TypeId } from "./types";

export type DexForm = {
  hp: number;
  attack: number;
  defense: number;
  spAtk: number;
  spDef: number;
  speed: number;
  types: TypeId[];
  moves: MoveId[];
};

export type DexRecord = {
  dexNumber: { nat: number };
  dexName: string;
  games: Record<GameId, boolean>;
  forms: { base: DexForm | null } & Partial<Record<FormId, DexForm | null>>;
};

export const dexObject: Record<number, DexRecord> = {
  3: {
    dexNumber: { nat: 3 },
    
    dexName: "Venusaur",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  6: {
    dexNumber: { nat: 6 },
    dexName: "Charizard",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  9: {
    dexNumber: { nat: 9 },
    dexName: "Blastoise",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  15: {
    dexNumber: { nat: 15 },
    dexName: "Beedrill",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  18: {
    dexNumber: { nat: 18 },
    dexName: "Pidgeot",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  24: {
    dexNumber: { nat: 24 },
    dexName: "Arbok",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  25: {
    dexNumber: { nat: 25 },
    dexName: "Pikachu",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  26: {
    dexNumber: { nat: 26 },
    dexName: "Raichu",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: {
        hp: 135,
        attack: 110,
        defense: 75,
        spAtk: 110,
        spDef: 100,
        speed: 130,
        types: [TYPES.electric],
        moves: []
      },
      [FORM_IDS.aloan]: {
        hp: 135,
        attack: 105,
        defense: 70,
        spAtk: 115,
        spDef: 105,
        speed: 130,
        types: [TYPES.electric, TYPES.psychic],
        moves: []
      },
    },
  },
  36: {
    dexNumber: { nat: 36 },
    dexName: "Clefable",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: {
        hp: 170,
        attack: 90,
        defense: 93,
        spAtk: 115,
        spDef: 110,
        speed: 80,
        types: [TYPES.fairy],
        moves: []
      },
    },
  },
  38: {
    dexNumber: { nat: 38 },
    dexName: "Ninetales",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.aloan]: {
        hp: 148,
        attack: 87,
        defense: 95,
        spAtk: 101,
        spDef: 120,
        speed: 129,
        types: [TYPES.ice, TYPES.fairy],
        moves: []
      },
    },
  },
  59: {
    dexNumber: { nat: 59 },
    dexName: "Arcanine",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: {
        hp: 165,
        attack: 130,
        defense: 100,
        spAtk: 120,
        spDef: 100,
        speed: 115,
        types: [TYPES.fire],
        moves: [
          MOVES.gigaImpact,
          MOVES.doubleEdge,
          MOVES.thrash,
          MOVES.bodySlam,
          MOVES.extremeSpeed,
          MOVES.facade,
          MOVES.covet,
          MOVES.hyperBeam,
          MOVES.hyperVoice,
          MOVES.round,
          MOVES.snore,
          MOVES.howl,
          MOVES.helpingHand,
          MOVES.morningSun,
          MOVES.sleepTalk,
          MOVES.endure,
          MOVES.scaryFace,
          MOVES.protect,
          MOVES.substitue,
          MOVES.roar,
          MOVES.solarBeam,
          MOVES.ragingFury,
          MOVES.flareBlitz,
          MOVES.temperFlare,
          MOVES.fireFang,
          MOVES.flameCharge,
          MOVES.heatCrash,
          MOVES.burnUp,
          MOVES.overheat,
          MOVES.fireBlast,
          MOVES.heatWave,
          MOVES.flamethrower,
          MOVES.fireSpin,
          MOVES.willOWisp,
          MOVES.sunnyDay,
          MOVES.wildCharge,
          MOVES.thunderFang,
          MOVES.aerialAce,
          MOVES.dig,
          MOVES.bulldoze,
          MOVES.scorchingSands,
          MOVES.closeCombat,
          MOVES.reversal,
          MOVES.psychicFangs,
          MOVES.rest,
          MOVES.agility,
          MOVES.curse,
          MOVES.outrage,
          MOVES.dragonPulse,
          MOVES.crunch,
          MOVES.thief,
          MOVES.bite,
          MOVES.snarl,
          MOVES.ironTail,
          MOVES.ironHead,
          MOVES.playRough,
          MOVES.charm,
        ],
      },
      [FORM_IDS.hisuian]: {
        hp: 170,
        attack: 135,
        defense: 100,
        spAtk: 115,
        spDef: 100,
        speed: 110,
        types: [TYPES.fire, TYPES.rock],
        moves: []
      },
    },
  },
  65: {
    dexNumber: { nat: 65 },
    dexName: "Alakazam",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  68: {
    dexNumber: { nat: 68 },
    dexName: "Machamp",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  71: {
    dexNumber: { nat: 71 },
    dexName: "Victreebel",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  80: {
    dexNumber: { nat: 80 },
    dexName: "Slowbro",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.galarian]: {
        hp: 170,
        attack: 120,
        defense: 115,
        spAtk: 120,
        spDef: 90,
        speed: 50,
        types: [TYPES.poison, TYPES.psychic],
        moves: []
      },
    },
  },
  94: {
    dexNumber: { nat: 94 },
    dexName: "Gengar",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: {
        hp: 135,
        attack: 85,
        defense: 80,
        spAtk: 150,
        spDef: 95,
        speed: 130,
        types: [TYPES.ghost, TYPES.poison],
        moves: [
          MOVES.selfDestruct,
          MOVES.gigaImpact,
          MOVES.bodySlam,
          MOVES.facade,
          MOVES.hyperBeam,
          MOVES.round,
          MOVES.snore,
          MOVES.reflectType,
          MOVES.psychUp,
          MOVES.painSplit,
          MOVES.sleepTalk,
          MOVES.meanLook,
          MOVES.endure,
          MOVES.perishSong,
          MOVES.scaryFace,
          MOVES.protect,
          MOVES.substitue,
          MOVES.disable,
          MOVES.energyBall,
          MOVES.gigaDrain,
          MOVES.firePunch,
          MOVES.willOWisp,
          MOVES.sunnyDay,
          MOVES.rainDance,
          MOVES.thunderPunch,
          MOVES.thunder,
          MOVES.thunderbolt,
          MOVES.thunderWave,
          MOVES.skitterSmack,
          MOVES.gunkShot,
          MOVES.poisonJab,
          MOVES.sludgeWave,
          MOVES.sludgeBomb,
          MOVES.venoshock,
          MOVES.clearSmog,
          MOVES.acidSpray,
          MOVES.corrosiveGas,
          MOVES.toxicSpikes,
          MOVES.toxic,
          MOVES.icePunch,
          MOVES.icyWind,
          MOVES.haze,
          MOVES.focusPunch,
          MOVES.drainPunch,
          MOVES.brickBreak,
          MOVES.focusBlast,
          MOVES.psychic,
          MOVES.psychicNoise,
          MOVES.wonderRoom,
          MOVES.trickRoom,
          MOVES.imprison,
          MOVES.skillSwap,
          MOVES.trick,
          MOVES.rest,
          MOVES.hypnosis,
          MOVES.poltergeist,
          MOVES.phantomForce,
          MOVES.shadowClaw,
          MOVES.shadowPunch,
          MOVES.shadowBall,
          MOVES.hex,
          MOVES.nightShade,
          MOVES.destinyBond,
          MOVES.spite,
          MOVES.curse,
          MOVES.confuseRay,
          MOVES.foulPlay,
          MOVES.suckerPunch,
          MOVES.knockOff,
          MOVES.thief,
          MOVES.payback,
          MOVES.fling,
          MOVES.darkPulse,
          MOVES.nastyPlot,
          MOVES.taunt,
          MOVES.dazzlingGleam,
        ]
      }
    },
  },
  115: {
    dexNumber: { nat: 115 },
    dexName: "Kangaskhan",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: {
        hp: 180,
        attack: 115,
        defense: 100,
        spAtk: 60,
        spDef: 100,
        speed: 110,
        types: [TYPES.normal],
        moves: [
          MOVES.gigaImpact,
          MOVES.lastResort,
          MOVES.doubleEdge,
          MOVES.megaKick,
          MOVES.bodySlam,
          MOVES.facade,
          MOVES.fakeOut,
          MOVES.doubleHit,
          MOVES.endeavor,
          MOVES.hyperBeam,
          MOVES.uproar,
          MOVES.round,
          MOVES.terrainPulse,
          MOVES.snore,
          MOVES.helpingHand,
          MOVES.safeGuard,
          MOVES.sleepTalk,
          MOVES.attract,
          MOVES.endure,
          MOVES.protect,
          MOVES.substitue,
          MOVES.focusEnergy,
          MOVES.disable,
          MOVES.solarBeam,
          MOVES.firePunch,
          MOVES.fireBlast,
          MOVES.flamethrower,
          MOVES.sunnyDay,
          MOVES.hydroPump,
          MOVES.surf,
          MOVES.whirlpool,
          MOVES.rainDance,
          MOVES.thunderPunch,
          MOVES.thunder,
          MOVES.thunderbolt,
          MOVES.rockSlide,
          MOVES.rockTomb,
          MOVES.sandstorm,
          MOVES.earthquake,
          MOVES.dig,
          MOVES.bulldoze,
          MOVES.icePunch,
          MOVES.avalanche,
          MOVES.blizzard,
          MOVES.iceBeam,
          MOVES.icyWind,
          MOVES.hammerArm,
          MOVES.dynamicPunch,
          MOVES.drainPunch,
          MOVES.brickBreak,
          MOVES.circleThrow,
          MOVES.reversal,
          MOVES.counter,
          MOVES.lowKick,
          MOVES.focusBlast,
          MOVES.rest,
          MOVES.shadowClaw,
          MOVES.shadowBall,
          MOVES.outrage,
          MOVES.crunch,
          MOVES.suckerPunch,
          MOVES.assurance,
          MOVES.thief,
          MOVES.bite,
          MOVES.fling,
          MOVES.beatUp,
          MOVES.ironTail,
        ],
      }
    },
  },
  121: {
    dexNumber: { nat: 121 },
    dexName: "Starmie",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: {
        hp: 135,
        attack: 95,
        defense: 105,
        spAtk: 120,
        spDef: 105,
        speed: 135,
        types: [TYPES.water, TYPES.psychic],
        moves: []
      },
    },
  },
  127: {
    dexNumber: { nat: 127 },
    dexName: "Pinsir",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: {
        hp: 140,
        attack: 145,
        defense: 120,
        spAtk: 75,
        spDef: 90,
        speed: 105,
        types: [TYPES.bug],
        moves: []
      },
    },
  },
  128: {
    dexNumber: { nat: 128 },
    dexName: "Tauros",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: {
        hp: 150,
        attack: 120,
        defense: 115,
        spAtk: 60,
        spDef: 90,
        speed: 130,
        types: [TYPES.normal],
        moves: []
      },
      [FORM_IDS.paldeanCombat]: null,
      [FORM_IDS.paldeanFire]: null,
      [FORM_IDS.paldeanWater]: null,
    },
  },
  130: {
    dexNumber: { nat: 130 },
    dexName: "Gyarados",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  132: {
    dexNumber: { nat: 132 },
    dexName: "Ditto",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  134: {
    dexNumber: { nat: 134 },
    dexName: "Vaporeon",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: {
        hp: 205,
        attack: 85,
        defense: 80,
        spAtk: 130,
        spDef: 115,
        speed: 85,
        types: [TYPES.water],
        moves: []
      },
    },
  },
  135: {
    dexNumber: { nat: 135 },
    dexName: "Jolteon",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: {
        hp: 140,
        attack: 85,
        defense: 80,
        spAtk: 130,
        spDef: 115,
        speed: 150,
        types: [TYPES.electric],
        moves: []
      },
    },
  },
  136: {
    dexNumber: { nat: 136 },
    dexName: "Flareon",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: {
        hp: 140,
        attack: 150,
        defense: 80,
        spAtk: 115,
        spDef: 130,
        speed: 85,
        types: [TYPES.fire],
        moves: []
      }
    },
  },
  142: {
    dexNumber: { nat: 142 },
    dexName: "Aerodactyl",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: {
        hp: 155,
        attack: 125,
        defense: 85,
        spAtk: 80,
        spDef: 95,
        speed: 150,
        types: [TYPES.rock, TYPES.flying],
        moves: []
      }
    },
  },
  143: {
    dexNumber: { nat: 143 },
    dexName: "Snorlax",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: {
        hp: 235,
        attack: 130,
        defense: 85,
        spAtk: 85,
        spDef: 130,
        speed: 50,
        types: [TYPES.normal],
        moves: []
      }
    },
  },
  149: {
    dexNumber: { nat: 149 },
    dexName: "Dragonite",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: {
        hp: 166,
        attack: 154,
        defense: 115,
        spAtk: 120,
        spDef: 120,
        speed: 100,
        types: [TYPES.dragon, TYPES.flying],
        moves: [
          MOVES.gigaImpact,
          MOVES.megaKick,
          MOVES.bodySlam,
          MOVES.extremeSpeed,
          MOVES.facade,
          MOVES.wrap,
          MOVES.hyperBeam,
          MOVES.round,
          MOVES.weatherBall,
          MOVES.snore,
          MOVES.helpingHand,
          MOVES.safeGuard,
          MOVES.sleepTalk,
          MOVES.endure,
          MOVES.scaryFace,
          MOVES.protect,
          MOVES.substitue,
          MOVES.roar,
          MOVES.whirlwind,
          MOVES.firePunch,
          MOVES.fireBlast,
          MOVES.heatWave,
          MOVES.flamethrower,
          MOVES.fireSpin,
          MOVES.sunnyDay,
          MOVES.aquaTail,
          MOVES.dive,
          MOVES.waterfall,
          MOVES.aquaJet,
          MOVES.hydroPump,
          MOVES.surf,
          MOVES.waterPulse,
          MOVES.chillingWater,
          MOVES.rainDance,
          MOVES.thunderPunch,
          MOVES.thunder,
          MOVES.thunderbolt,
          MOVES.thunderWave,
          MOVES.fly,
          MOVES.aerialAce,
          MOVES.hurricane,
          MOVES.airSlash,
          MOVES.airCutter,
          MOVES.tailwind,
          MOVES.roost,
          MOVES.stoneEdge,
          MOVES.rockSlide,
          MOVES.rockTomb,
          MOVES.sandstorm,
          MOVES.earthquake,
          MOVES.stompingTantrum,
          MOVES.bulldoze,
          MOVES.iceSpinner,
          MOVES.icePunch,
          MOVES.blizzard,
          MOVES.iceBeam,
          MOVES.icyWind,
          MOVES.snowscape,
          MOVES.haze,
          MOVES.focusPunch,
          MOVES.superPower,
          MOVES.bodyPress,
          MOVES.brickBreak,
          MOVES.lowKick,
          MOVES.focusBlast,
          MOVES.rest,
          MOVES.lightScreen,
          MOVES.agility,
          MOVES.outrage,
          MOVES.dragonRush,
          MOVES.dragonClaw,
          MOVES.breakingSwipe,
          MOVES.dragonTail,
          MOVES.scaleShot,
          MOVES.dracoMeteor,
          MOVES.dragonPulse,
          MOVES.dragonCheer,
          MOVES.dragonDance,
          MOVES.brutalSwing,
          MOVES.fling,
          MOVES.ironTail,
          MOVES.ironHead,
          MOVES.steelWing,
        ],
      }
    },
  },
  154: {
    dexNumber: { nat: 154 },
    dexName: "Meganium",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  157: {
    dexNumber: { nat: 157 },
    dexName: "Typhlosion",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.hisuian]: null,
    },
  },
  160: {
    dexNumber: { nat: 160 },
    dexName: "Feraligatr",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  168: {
    dexNumber: { nat: 168 },
    dexName: "Ariados",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  181: {
    dexNumber: { nat: 181 },
    dexName: "Ampharos",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: {
        hp: 165,
        attack: 95,
        defense: 105,
        spAtk: 135,
        spDef: 110,
        speed: 75,
        types: [TYPES.electric],
        moves: [
          MOVES.gigaImpact,
          MOVES.doubleEdge,
          MOVES.megaKick,
          MOVES.bodySlam,
          MOVES.facade,
          MOVES.endeavor,
          MOVES.hyperBeam,
          MOVES.round,
          MOVES.snore,
          MOVES.afterYou,
          MOVES.helpingHand,
          MOVES.safeguard,
          MOVES.sleepTalk,
          MOVES.endure,
          MOVES.protect,
          MOVES.substitue,
          MOVES.screech,
          MOVES.roar,
          MOVES.trailblaze,
          MOVES.cottonGuard,
          MOVES.cottonSpore,
          MOVES.firePunch,
          MOVES.sunnyDay,
          MOVES.rainDance,
          MOVES.supercellSlam,
          MOVES.wildCharge,
          MOVES.thunderPunch,
          MOVES.zapCannon,
          MOVES.thunder,
          MOVES.thunderbolt,
          MOVES.discharge,
          MOVES.risingVoltage,
          MOVES.voltSwitch,
          MOVES.parabolicCharge,
          MOVES.electroweb,
          MOVES.chargeBeam,
          MOVES.electroBall,
          MOVES.electricTerrain,
          MOVES.magneticFlux,
          MOVES.eerieImpulse,
          MOVES.charge,
          MOVES.thunderWave,
          MOVES.meteorBeam,
          MOVES.powerGem,
          MOVES.dig,
          MOVES.stompingTantrum,
          MOVES.bulldoze,
          MOVES.icePunch,
          MOVES.focusPunch,
          MOVES.brickBreak,
          MOVES.lowKick,
          MOVES.focusBlast,
          MOVES.rest,
          MOVES.reflect,
          MOVES.lightScreen,
          MOVES.agility,
          MOVES.confuseRay,
          MOVES.outrage,
          MOVES.breakingSwipe,
          MOVES.dragonTail,
          MOVES.dragonPulse,
          MOVES.dragonCheer,
          MOVES.brutalSwing,
          MOVES.fling,
          MOVES.flatter,
          MOVES.ironTail,
          MOVES.dazzlingGleam,
        ],
      }
    },
  },
  184: {
    dexNumber: { nat: 184 },
    dexName: "Azumarill",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  186: {
    dexNumber: { nat: 186 },
    dexName: "Politoed",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  196: {
    dexNumber: { nat: 196 },
    dexName: "Espeon",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  197: {
    dexNumber: { nat: 197 },
    dexName: "Umbreon",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  199: {
    dexNumber: { nat: 199 },
    dexName: "Slowking",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.galarian]: null,
    },
  },
  205: {
    dexNumber: { nat: 205 },
    dexName: "Forretress",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  208: {
    dexNumber: { nat: 208 },
    dexName: "Steelix",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  212: {
    dexNumber: { nat: 212 },
    dexName: "Scizor",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  214: {
    dexNumber: { nat: 214 },
    dexName: "Heracross",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  227: {
    dexNumber: { nat: 227 },
    dexName: "Skarmory",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  229: {
    dexNumber: { nat: 229 },
    dexName: "Houndoom",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  248: {
    dexNumber: { nat: 248 },
    dexName: "Tyranitar",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  279: {
    dexNumber: { nat: 279 },
    dexName: "Pelipper",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  282: {
    dexNumber: { nat: 282 },
    dexName: "Gardevoir",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  302: {
    dexNumber: { nat: 302 },
    dexName: "Sableye",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  306: {
    dexNumber: { nat: 306 },
    dexName: "Aggron",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  308: {
    dexNumber: { nat: 308 },
    dexName: "Medicham",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  310: {
    dexNumber: { nat: 310 },
    dexName: "Manectric",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  319: {
    dexNumber: { nat: 319 },
    dexName: "Sharpedo",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  323: {
    dexNumber: { nat: 323 },
    dexName: "Camerupt",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  324: {
    dexNumber: { nat: 324 },
    dexName: "Torkoal",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  334: {
    dexNumber: { nat: 334 },
    dexName: "Altaria",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  350: {
    dexNumber: { nat: 350 },
    dexName: "Milotic",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  351: {
    dexNumber: { nat: 351 },
    dexName: "Castform",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  354: {
    dexNumber: { nat: 354 },
    dexName: "Banette",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  358: {
    dexNumber: { nat: 358 },
    dexName: "Chimecho",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  359: {
    dexNumber: { nat: 359 },
    dexName: "Absol",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  362: {
    dexNumber: { nat: 362 },
    dexName: "Glalie",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  389: {
    dexNumber: { nat: 389 },
    dexName: "Torterra",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  392: {
    dexNumber: { nat: 392 },
    dexName: "Infernape",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  395: {
    dexNumber: { nat: 395 },
    dexName: "Empoleon",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  405: {
    dexNumber: { nat: 405 },
    dexName: "Luxray",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  407: {
    dexNumber: { nat: 407 },
    dexName: "Roserade",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  409: {
    dexNumber: { nat: 409 },
    dexName: "Rampardos",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  411: {
    dexNumber: { nat: 411 },
    dexName: "Bastiodon",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  428: {
    dexNumber: { nat: 428 },
    dexName: "Lopunny",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  442: {
    dexNumber: { nat: 442 },
    dexName: "Spiritomb",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  445: {
    dexNumber: { nat: 445 },
    dexName: "Garchomp",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  448: {
    dexNumber: { nat: 448 },
    dexName: "Lucario",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  450: {
    dexNumber: { nat: 450 },
    dexName: "Hippowdon",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  454: {
    dexNumber: { nat: 454 },
    dexName: "Toxicroak",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  460: {
    dexNumber: { nat: 460 },
    dexName: "Abomasnow",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  461: {
    dexNumber: { nat: 461 },
    dexName: "Weavile",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  464: {
    dexNumber: { nat: 464 },
    dexName: "Rhyperior",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  470: {
    dexNumber: { nat: 470 },
    dexName: "Leafeon",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  471: {
    dexNumber: { nat: 471 },
    dexName: "Glaceon",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  472: {
    dexNumber: { nat: 472 },
    dexName: "Gliscor",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  473: {
    dexNumber: { nat: 473 },
    dexName: "Mamoswine",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  475: {
    dexNumber: { nat: 475 },
    dexName: "Gallade",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  478: {
    dexNumber: { nat: 478 },
    dexName: "Froslass",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  479: {
    dexNumber: { nat: 479 },
    dexName: "Rotom",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.heat]: null,
      [FORM_IDS.wash]: null,
      [FORM_IDS.frost]: null,
      [FORM_IDS.fan]: null,
      [FORM_IDS.grass]: null,
    },
  },
  497: {
    dexNumber: { nat: 497 },
    dexName: "Serperior",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  500: {
    dexNumber: { nat: 500 },
    dexName: "Emboar",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  503: {
    dexNumber: { nat: 503 },
    dexName: "Samurott",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.hisuian]: null,
    },
  },
  505: {
    dexNumber: { nat: 505 },
    dexName: "Watchog",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  510: {
    dexNumber: { nat: 510 },
    dexName: "Liepard",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  512: {
    dexNumber: { nat: 512 },
    dexName: "Simisage",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  514: {
    dexNumber: { nat: 514 },
    dexName: "Simisear",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  516: {
    dexNumber: { nat: 516 },
    dexName: "Simipour",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  530: {
    dexNumber: { nat: 530 },
    dexName: "Excadrill",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  531: {
    dexNumber: { nat: 531 },
    dexName: "Audino",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  534: {
    dexNumber: { nat: 534 },
    dexName: "Conkeldurr",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  547: {
    dexNumber: { nat: 547 },
    dexName: "Whimsicott",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: {
        hp: 135,
        attack: 87,
        defense: 105,
        spAtk: 97,
        spDef: 95,
        speed: 136,
        types: [TYPES.grass, TYPES.fairy],
        moves: [
          MOVES.gigaImpact,
          MOVES.facade,
          MOVES.endeavor,
          MOVES.hyperBeam,
          MOVES.round,
          MOVES.snore,
          MOVES.tickle,
          MOVES.helpingHand,
          MOVES.encore,
          MOVES.safeGuard,
          MOVES.sleepTalk,
          MOVES.attract,
          MOVES.endure,
          MOVES.protect,
          MOVES.substitue,
          MOVES.seedBomb,
          MOVES.grassyGlide,
          MOVES.solarBeam,
          MOVES.energyBall,
          MOVES.gigaDrain,
          MOVES.grassKnot,
          MOVES.grassyTerrain,
          MOVES.cottonGuard,
          MOVES.worrySeed,
          MOVES.cottonSpore,
          MOVES.stunSpore,
          MOVES.growth,
          MOVES.leechSeed,
          MOVES.sunnyDay,
          MOVES.uTurn,
          MOVES.hurricane,
          MOVES.tailwind,
          MOVES.poisonPowder,
          MOVES.psychic,
          MOVES.trickRoom,
          MOVES.rest,
          MOVES.lightScreen,
          MOVES.shadowBall,
          MOVES.thief,
          MOVES.fling,
          MOVES.beatUp,
          MOVES.switcheroo,
          MOVES.fakeTears,
          MOVES.taunt,
          MOVES.memento,
          MOVES.playRough,
          MOVES.moonblast,
          MOVES.dazzlingGleam,
          MOVES.mistyTerrain,
          MOVES.charm,
        ]
      }
    },
  },
  553: {
    dexNumber: { nat: 553 },
    dexName: "Krookodile",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  563: {
    dexNumber: { nat: 563 },
    dexName: "Cofagrigus",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  569: {
    dexNumber: { nat: 569 },
    dexName: "Garbodor",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  571: {
    dexNumber: { nat: 571 },
    dexName: "Zoroark",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.hisuian]: null,
    },
  },
  579: {
    dexNumber: { nat: 579 },
    dexName: "Reuniclus",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  584: {
    dexNumber: { nat: 584 },
    dexName: "Vanilluxe",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  587: {
    dexNumber: { nat: 587 },
    dexName: "Emolga",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  609: {
    dexNumber: { nat: 609 },
    dexName: "Chandelure",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  614: {
    dexNumber: { nat: 614 },
    dexName: "Beartic",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  618: {
    dexNumber: { nat: 618 },
    dexName: "Stunfisk",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.galarian]: null,
    },
  },
  623: {
    dexNumber: { nat: 623 },
    dexName: "Golurk",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  635: {
    dexNumber: { nat: 635 },
    dexName: "Hydreigon",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  637: {
    dexNumber: { nat: 637 },
    dexName: "Volcarona",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  652: {
    dexNumber: { nat: 652 },
    dexName: "Chesnaught",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  655: {
    dexNumber: { nat: 655 },
    dexName: "Delphox",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  658: {
    dexNumber: { nat: 658 },
    dexName: "Greninja",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  660: {
    dexNumber: { nat: 660 },
    dexName: "Diggersby",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  663: {
    dexNumber: { nat: 663 },
    dexName: "Talonflame",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  666: {
    dexNumber: { nat: 666 },
    dexName: "Vivillon",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  670: {
    dexNumber: { nat: 670 },
    dexName: "Floette",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  671: {
    dexNumber: { nat: 671 },
    dexName: "Florges",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  675: {
    dexNumber: { nat: 675 },
    dexName: "Pangoro",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  676: {
    dexNumber: { nat: 676 },
    dexName: "Furfrou",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  678: {
    dexNumber: { nat: 678 },
    dexName: "Meowstic",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.female]: null,
    },
  },
  681: {
    dexNumber: { nat: 681 },
    dexName: "Aegislash",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  683: {
    dexNumber: { nat: 683 },
    dexName: "Aromatisse",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  685: {
    dexNumber: { nat: 685 },
    dexName: "Slurpuff",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  693: {
    dexNumber: { nat: 693 },
    dexName: "Clawitzer",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  695: {
    dexNumber: { nat: 695 },
    dexName: "Heliolisk",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  697: {
    dexNumber: { nat: 697 },
    dexName: "Tyrantrum",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  699: {
    dexNumber: { nat: 699 },
    dexName: "Aurorus",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: {
        hp: 198,
        attack: 97,
        defense: 92,
        spAtk: 119,
        spDef: 112,
        speed: 78,
        types: [TYPES.rock, TYPES.ice],
        moves: [
          MOVES.gigaImpact,
          MOVES.bodySlam,
          MOVES.facade,
          MOVES.hyperBeam,
          MOVES.hyperVoice,
          MOVES.round,
          MOVES.weatherBall,
          MOVES.snore,
          MOVES.encore,
          MOVES.safeguard,
          MOVES.sleepTalk,
          MOVES.attract,
          MOVES.endure,
          MOVES.protect,
          MOVES.substitue,
          MOVES.chillingWater,
          MOVES.rainDance,
          MOVES.thunder,
          MOVES.thunderbolt,
          MOVES.discharge,
          MOVES.thunderWave,
          MOVES.stoneEdge,
          MOVES.rockSlide,
          MOVES.rockTomb,
          MOVES.rockBlast,
          MOVES.meteorBeam,
          MOVES.ancientPower,
          MOVES.stealthRock,
          MOVES.sandstorm,
          MOVES.earthquake,
          MOVES.bulldoze,
          MOVES.earthPower,
          MOVES.mudShot,
          MOVES.iceSpinner,
          MOVES.avalanche,
          MOVES.icicleSpear,
          MOVES.blizzard,
          MOVES.iceBeam,
          MOVES.freezeDry,
          MOVES.icyWind,
          MOVES.snowscape,
          MOVES.auroraVeil,
          MOVES.haze,
          MOVES.zenHeadbutt,
          MOVES.psychic,
          MOVES.mirrorCoat,
          MOVES.calmMind,
          MOVES.rest,
          MOVES.lightScreen,
          MOVES.outrage,
          MOVES.darkPulse,
          MOVES.ironTail,
          MOVES.ironHead,
          MOVES.flashCannon,
          MOVES.ironDefense
        ],
      }
    },
  },
  700: {
    dexNumber: { nat: 700 },
    dexName: "Sylveon",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: {
        hp: 170,
        attack: 85,
        defense: 85,
        spAtk: 130,
        spDef: 150,
        speed: 80,
        types: [TYPES.fairy],
        moves: [
          MOVES.gigaImpact,
          MOVES.lastResort,
          MOVES.doubleEdge,
          MOVES.bodySlam,
          MOVES.facade,
          MOVES.covet,
          MOVES.quickAttack,
          MOVES.flail,
          MOVES.hyperBeam,
          MOVES.hyperVoice,
          MOVES.round,
          MOVES.weatherBall,
          MOVES.snore,
          MOVES.copycat,
          MOVES.tickle,
          MOVES.yawn,
          MOVES.wish,
          MOVES.helpingHand,
          MOVES.psychUp,
          MOVES.batonPass,
          MOVES.safeguard,
          MOVES.sleepTalk,
          MOVES.endure,
          MOVES.protect,
          MOVES.substitue,
          MOVES.focusEnergy,
          MOVES.roar,
          MOVES.trailblaze,
          MOVES.mysticalFire,
          MOVES.sunnyDay,
          MOVES.rainDance,
          MOVES.dig,
          MOVES.mudSlap,
          MOVES.detect,
          MOVES.psychic,
          MOVES.psyshock,
          MOVES.storedPower,
          MOVES.calmMind,
          MOVES.skillSwap,
          MOVES.rest,
          MOVES.reflect,
          MOVES.lightScreen,
          MOVES.shadowBall,
          MOVES.curse,
          MOVES.bite,
          MOVES.fakeTears,
          MOVES.playRough,
          MOVES.mistyExplosion,
          MOVES.moonblast,
          MOVES.alluringVoice,
          MOVES.dazzlingGleam,
          MOVES.drainingKiss,
          MOVES.babyDollEyes,
          MOVES.mistyTerrain,
          MOVES.charm,
        ],
      }
    },
  },
  701: {
    dexNumber: { nat: 701 },
    dexName: "Hawlucha",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  702: {
    dexNumber: { nat: 702 },
    dexName: "Dedenne",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  706: {
    dexNumber: { nat: 706 },
    dexName: "Goodra",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.hisuian]: null,
    },
  },
  707: {
    dexNumber: { nat: 707 },
    dexName: "Klefki",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  709: {
    dexNumber: { nat: 709 },
    dexName: "Trevenant",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  711: {
    dexNumber: { nat: 711 },
    dexName: "Gourgeist",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.medium]: null,
      [FORM_IDS.small]: null,
      [FORM_IDS.large]: null,
      [FORM_IDS.jumbo]: null,
    },
  },
  713: {
    dexNumber: { nat: 713 },
    dexName: "Avalugg",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.hisuian]: null,
    },
  },
  715: {
    dexNumber: { nat: 715 },
    dexName: "Noivern",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: {
        hp: 160,
        attack: 90,
        defense: 100,
        spAtk: 117,
        spDef: 100,
        speed: 143,
        types: [TYPES.flying, TYPES.dragon],
        moves: [
          MOVES.gigaImpact,
          MOVES.doubleEdge,
          MOVES.bodySlam,
          MOVES.facade,
          MOVES.superFang,
          MOVES.hyperBeam,
          MOVES.boomburst,
          MOVES.uproar,
          MOVES.round,
          MOVES.snore,
          MOVES.sleepTalk,
          MOVES.endure,
          MOVES.scaryFace,
          MOVES.protect,
          MOVES.substitue,
          MOVES.doubleTeam,
          MOVES.screech,
          MOVES.whirlwind,
          MOVES.solarBeam,
          MOVES.heatWave,
          MOVES.flamethrower,
          MOVES.sunnyDay,
          MOVES.waterPulse,
          MOVES.wildCharge,
          MOVES.xScissor,
          MOVES.leechLife,
          MOVES.uTurn,
          MOVES.skyAttack,
          MOVES.fly,
          MOVES.aerialAce,
          MOVES.acrobatics,
          MOVES.dualWingbeat,
          MOVES.hurricane,
          MOVES.airSlash,
          MOVES.airCutter,
          MOVES.defog,
          MOVES.tailwind,
          MOVES.roost,
          MOVES.brickBreak,
          MOVES.focusBlast,
          MOVES.psychic,
          MOVES.psychicNoise,
          MOVES.rest,
          MOVES.agility,
          MOVES.shadowClaw,
          MOVES.shadowBall,
          MOVES.outrage,
          MOVES.dragonRush,
          MOVES.dragonClaw,
          MOVES.breakingSwipe,
          MOVES.dragonTail,
          MOVES.dracoMeteor,
          MOVES.dragonPulse,
          MOVES.dragonCheer,
          MOVES.dragonDance,
          MOVES.thief,
          MOVES.bite,
          MOVES.darkPulse,
          MOVES.switcheroo,
          MOVES.taunt,
          MOVES.ironTail,
          MOVES.steelWing,
          MOVES.moonlight,
        ],
      }
    },
  },
  724: {
    dexNumber: { nat: 724 },
    dexName: "Decidueye",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.hisuian]: null,
    },
  },
  727: {
    dexNumber: { nat: 727 },
    dexName: "Incineroar",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  730: {
    dexNumber: { nat: 730 },
    dexName: "Primarina",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  733: {
    dexNumber: { nat: 733 },
    dexName: "Toucannon",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  740: {
    dexNumber: { nat: 740 },
    dexName: "Crabominable",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  745: {
    dexNumber: { nat: 745 },
    dexName: "Lycanroc",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.midnight]: null,
      [FORM_IDS.dusk]: null,
    },
  },
  748: {
    dexNumber: { nat: 748 },
    dexName: "Toxapex",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  750: {
    dexNumber: { nat: 750 },
    dexName: "Mudsdale",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  752: {
    dexNumber: { nat: 752 },
    dexName: "Araquanid",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  758: {
    dexNumber: { nat: 758 },
    dexName: "Salazzle",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  763: {
    dexNumber: { nat: 763 },
    dexName: "Tsareena",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  765: {
    dexNumber: { nat: 765 },
    dexName: "Oranguru",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  766: {
    dexNumber: { nat: 766 },
    dexName: "Passimian",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  778: {
    dexNumber: { nat: 778 },
    dexName: "Mimikyu",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  780: {
    dexNumber: { nat: 780 },
    dexName: "Drampa",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  784: {
    dexNumber: { nat: 784 },
    dexName: "Kommo O",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  823: {
    dexNumber: { nat: 823 },
    dexName: "Corviknight",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  841: {
    dexNumber: { nat: 841 },
    dexName: "Flapple",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  842: {
    dexNumber: { nat: 842 },
    dexName: "Appletun",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  844: {
    dexNumber: { nat: 844 },
    dexName: "Sandaconda",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  855: {
    dexNumber: { nat: 855 },
    dexName: "Polteageist",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  858: {
    dexNumber: { nat: 858 },
    dexName: "Hatterene",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  866: {
    dexNumber: { nat: 866 },
    dexName: "Mr Rime",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  867: {
    dexNumber: { nat: 867 },
    dexName: "Runerigus",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  869: {
    dexNumber: { nat: 869 },
    dexName: "Alcremie",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  877: {
    dexNumber: { nat: 877 },
    dexName: "Morpeko",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  887: {
    dexNumber: { nat: 887 },
    dexName: "Dragapult",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  899: {
    dexNumber: { nat: 899 },
    dexName: "Wyrdeer",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  900: {
    dexNumber: { nat: 900 },
    dexName: "Kleavor",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  902: {
    dexNumber: { nat: 902 },
    dexName: "Basculegion",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.female]: null,
    },
  },
  903: {
    dexNumber: { nat: 903 },
    dexName: "Sneasler",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  908: {
    dexNumber: { nat: 908 },
    dexName: "Meowscarada",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  911: {
    dexNumber: { nat: 911 },
    dexName: "Skeledirge",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  914: {
    dexNumber: { nat: 914 },
    dexName: "Quaquaval",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  925: {
    dexNumber: { nat: 925 },
    dexName: "Maushold",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  934: {
    dexNumber: { nat: 934 },
    dexName: "Garganacl",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  936: {
    dexNumber: { nat: 936 },
    dexName: "Armarouge",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  937: {
    dexNumber: { nat: 937 },
    dexName: "Ceruledge",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: {
        hp: 150,
        attack: 145,
        defense: 100,
        spAtk: 80,
        spDef: 120,
        speed: 105,
        types: [TYPES.fire, TYPES.ghost],
        moves: [
          MOVES.gigaImpact,
          MOVES.facade,
          MOVES.helpingHand,
          MOVES.psychUp,
          MOVES.sleepTalk,
          MOVES.endure,
          MOVES.protect,
          MOVES.substitue,
          MOVES.disable,
          MOVES.swordsDance,
          MOVES.solarBlade,
          MOVES.flareBlitz,
          MOVES.bitterBlade,
          MOVES.flameCharge,
          MOVES.burnUp,
          MOVES.overheat,
          MOVES.fireBlast,
          MOVES.heatWave,
          MOVES.flamethrower,
          MOVES.lavaPlume,
          MOVES.fireSpin,
          MOVES.willOWisp,
          MOVES.sunnyDay,
          MOVES.xScissor,
          MOVES.poisonJab,
          MOVES.clearSmog,
          MOVES.closeCombat,
          MOVES.brickBreak,
          MOVES.vacuumWave,
          MOVES.quickGuard,
          MOVES.bulkUp,
          MOVES.psychoCut,
          MOVES.storedPower,
          MOVES.allySwitch,
          MOVES.rest,
          MOVES.reflect,
          MOVES.lightScreen,
          MOVES.poltergeist,
          MOVES.phantomForce,
          MOVES.shadowClaw,
          MOVES.shadowSneak,
          MOVES.shadowBall,
          MOVES.hex,
          MOVES.nightShade,
          MOVES.destinyBond,
          MOVES.spite,
          MOVES.curse,
          MOVES.confuseRay,
          MOVES.dragonClaw,
          MOVES.throatChop,
          MOVES.nightSlash,
          MOVES.fling,
          MOVES.taunt,
          MOVES.ironHead,
          MOVES.ironDefense,
        ],
      },
    },
  },
  939: {
    dexNumber: { nat: 939 },
    dexName: "Bellibolt",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  952: {
    dexNumber: { nat: 952 },
    dexName: "Scovillain",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  956: {
    dexNumber: { nat: 956 },
    dexName: "Espathra",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  959: {
    dexNumber: { nat: 959 },
    dexName: "Tinkaton",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  964: {
    dexNumber: { nat: 964 },
    dexName: "Palafin",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  968: {
    dexNumber: { nat: 968 },
    dexName: "Orthworm",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  970: {
    dexNumber: { nat: 970 },
    dexName: "Glimmora",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  981: {
    dexNumber: { nat: 981 },
    dexName: "Farigiraf",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  983: {
    dexNumber: { nat: 983 },
    dexName: "Kingambit",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  1013: {
    dexNumber: { nat: 1013 },
    dexName: "Sinistcha",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
  1018: {
    dexNumber: { nat: 1018 },
    dexName: "Archaludon",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: {
      [FORM_IDS.base]: {
        hp: 165,
        attack: 125,
        defense: 150,
        spAtk: 145,
        spDef: 85,
        speed: 105,
        types: [TYPES.steel, TYPES.dragon],
        moves: [
          MOVES.gigaImpact,
          MOVES.doubleEdge,
          MOVES.bodySlam,
          MOVES.facade,
          MOVES.hyperBeam,
          MOVES.sleepTalk,
          MOVES.endure,
          MOVES.scaryFace,
          MOVES.protect,
          MOVES.substitue,
          MOVES.focusEnergy,
          MOVES.roar,
          MOVES.swordsDance,
          MOVES.solarBeam,
          MOVES.electroShot,
          MOVES.thunder,
          MOVES.thunderbolt,
          MOVES.thunderWave,
          MOVES.stoneEdge,
          MOVES.rockSlide,
          MOVES.rockTomb,
          MOVES.smackDown,
          MOVES.meteorBeam,
          MOVES.stealthRock,
          MOVES.earthquake,
          MOVES.brickBreak,
          MOVES.auraSphere,
          MOVES.mirrorCoat,
          MOVES.rest,
          MOVES.reflect,
          MOVES.lightScreen,
          MOVES.outrage,
          MOVES.dragonClaw,
          MOVES.breakingSwipe,
          MOVES.dragonTail,
          MOVES.dracoMeteor,
          MOVES.dragonPulse,
          MOVES.dragonCheer,
          MOVES.foulPlay,
          MOVES.nightSlash,
          MOVES.darkPulse,
          MOVES.snarl,
          MOVES.ironHead,
          MOVES.hardPress,
          MOVES.heavySlam,
          MOVES.metalBurst,
          MOVES.gyroBall,
          MOVES.steelBeam,
          MOVES.flashCannon,
          MOVES.ironDefense,
          MOVES.metalSound,
        ]
      },
    },
  },
  1019: {
    dexNumber: { nat: 1019 },
    dexName: "Hydrapple",
    games: { [GAME_IDS.CHAMPIONS]: true },
    forms: { [FORM_IDS.base]: null },
  },
};

export function getDexIds(): number[] {
  return Object.keys(dexObject)
    .map((k) => Number(k))
    .filter((n) => Number.isFinite(n))
    .sort((a, b) => a - b);
}

