import { FORM_IDS } from "./constants";
import type { FormId } from "./constants";
import { MOVES } from "./moves";
import type { MoveId } from "./moves";
import { TYPES } from "./types";
import type { TypeId } from "./types";

export type DexForm = {
  hp: number;
  attack: number;
  defense: number;
  spAtk: number;
  spDef: number;
  speed: number;
  types: TypeId[];
  moves: MoveId[];
};

export type DexRecord = {
  dexNumber: number;
  dexName: string;
  forms: { base: DexForm | null } & Partial<Record<FormId, DexForm | null>>;
};

/**
 * Dex data source keyed by record id.
 *
 * Note: JS object keys are strings at runtime; we keep the type as `Record<number, ...>`
 * so consuming code can treat ids as numbers ergonomically.
 */
export const dexObject: Record<number, DexRecord> = {
  3: {
    dexNumber: 3,
    dexName: "Venusaur",
    forms: { [FORM_IDS.base]: null },
  },
  6: {
    dexNumber: 6,
    dexName: "Charizard",
    forms: { [FORM_IDS.base]: null },
  },
  9: {
    dexNumber: 9,
    dexName: "Blastoise",
    forms: { [FORM_IDS.base]: null },
  },
  15: {
    dexNumber: 15,
    dexName: "Beedrill",
    forms: { [FORM_IDS.base]: null },
  },
  18: {
    dexNumber: 18,
    dexName: "Pidgeot",
    forms: { [FORM_IDS.base]: null },
  },
  24: {
    dexNumber: 24,
    dexName: "Arbok",
    forms: { [FORM_IDS.base]: null },
  },
  25: {
    dexNumber: 25,
    dexName: "Pikachu",
    forms: { [FORM_IDS.base]: null },
  },
  26: {
    dexNumber: 26,
    dexName: "Raichu",
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.aloan]: null,
    },
  },
  36: {
    dexNumber: 36,
    dexName: "Clefable",
    forms: { [FORM_IDS.base]: null },
  },
  38: {
    dexNumber: 38,
    dexName: "Ninetales",
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.aloan]: null,
    },
  },
  59: {
    dexNumber: 59,
    dexName: "Arcanine",
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.hisuian]: null,
    },
  },
  65: {
    dexNumber: 65,
    dexName: "Alakazam",
    forms: { [FORM_IDS.base]: null },
  },
  68: {
    dexNumber: 68,
    dexName: "Machamp",
    forms: { [FORM_IDS.base]: null },
  },
  71: {
    dexNumber: 71,
    dexName: "Victreebel",
    forms: { [FORM_IDS.base]: null },
  },
  80: {
    dexNumber: 80,
    dexName: "Slowbro",
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.galarian]: null,
    },
  },
  94: {
    dexNumber: 94,
    dexName: "Gengar",
    forms: { [FORM_IDS.base]: null },
  },
  115: {
    dexNumber: 115,
    dexName: "Kangaskhan",
    forms: {
      [FORM_IDS.base]: {
        hp: 180,
        attack: 115,
        defense: 100,
        spAtk: 60,
        spDef: 100,
        speed: 110,
        types: [TYPES.normal],
        moves: [
          MOVES.gigaImpact,
          MOVES.lastResort,
          MOVES.doubleEdge,
          MOVES.megaKick,
          MOVES.bodySlam,
          MOVES.facade,
          MOVES.fakeOut,
          MOVES.doubleHit,
          MOVES.endeavor,
          MOVES.hyperBeam,
          MOVES.uproar,
          MOVES.round,
          MOVES.terrainPulse,
          MOVES.snore,
          MOVES.helpingHand,
          MOVES.safeGuard,
          MOVES.sleepTalk,
          MOVES.attract,
          MOVES.endure,
          MOVES.protect,
          MOVES.substitue,
          MOVES.focusEnergy,
          MOVES.disable,
          MOVES.solarBeam,
          MOVES.firePunch,
          MOVES.fireBlast,
          MOVES.flamethrower,
          MOVES.sunnyDay,
          MOVES.hydroPump,
          MOVES.surf,
          MOVES.whirlpool,
          MOVES.rainDance,
          MOVES.thunderPunch,
          MOVES.thunder,
          MOVES.thunderbolt,
          MOVES.rockSlide,
          MOVES.rockTomb,
          MOVES.sandstorm,
          MOVES.earthquake,
          MOVES.dig,
          MOVES.bulldoze,
          MOVES.icePunch,
          MOVES.avalanche,
          MOVES.blizzard,
          MOVES.iceBeam,
          MOVES.icyWind,
          MOVES.hammerArm,
          MOVES.dynamicPunch,
          MOVES.drainPunch,
          MOVES.brickBreak,
          MOVES.circleThrow,
          MOVES.reversal,
          MOVES.counter,
          MOVES.lowKick,
          MOVES.focusBlast,
          MOVES.rest,
          MOVES.shadowClaw,
          MOVES.shadowBall,
          MOVES.outrage,
          MOVES.crunch,
          MOVES.suckerPunch,
          MOVES.assurance,
          MOVES.thief,
          MOVES.bite,
          MOVES.fling,
          MOVES.beatUp,
          MOVES.ironTail,
        ],
      }
    },
  },
  121: {
    dexNumber: 121,
    dexName: "Starmie",
    forms: { [FORM_IDS.base]: null },
  },
  127: {
    dexNumber: 127,
    dexName: "Pinsir",
    forms: { [FORM_IDS.base]: null },
  },
  128: {
    dexNumber: 128,
    dexName: "Tauros",
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.paldeanCombat]: null,
      [FORM_IDS.paldeanFire]: null,
      [FORM_IDS.paldeanWater]: null,
    },
  },
  130: {
    dexNumber: 130,
    dexName: "Gyarados",
    forms: { [FORM_IDS.base]: null },
  },
  132: {
    dexNumber: 132,
    dexName: "Ditto",
    forms: { [FORM_IDS.base]: null },
  },
  134: {
    dexNumber: 134,
    dexName: "Vaporeon",
    forms: { [FORM_IDS.base]: null },
  },
  135: {
    dexNumber: 135,
    dexName: "Jolteon",
    forms: { [FORM_IDS.base]: null },
  },
  136: {
    dexNumber: 136,
    dexName: "Flareon",
    forms: { [FORM_IDS.base]: null },
  },
  142: {
    dexNumber: 142,
    dexName: "Aerodactyl",
    forms: { [FORM_IDS.base]: null },
  },
  143: {
    dexNumber: 143,
    dexName: "Snorlax",
    forms: { [FORM_IDS.base]: null },
  },
  149: {
    dexNumber: 149,
    dexName: "Dragonite",
    forms: {
      [FORM_IDS.base]: {
        hp: 166,
        attack: 154,
        defense: 115,
        spAtk: 120,
        spDef: 120,
        speed: 100,
        types: [TYPES.dragon, TYPES.flying],
        moves: [
          MOVES.gigaImpact,
          MOVES.megaKick,
          MOVES.bodySlam,
          MOVES.extremeSpeed,
          MOVES.facade,
          MOVES.wrap,
          MOVES.hyperBeam,
          MOVES.round,
          MOVES.weatherBall,
          MOVES.snore,
          MOVES.helpingHand,
          MOVES.safeGuard,
          MOVES.sleepTalk,
          MOVES.endure,
          MOVES.scaryFace,
          MOVES.protect,
          MOVES.substitue,
          MOVES.roar,
          MOVES.whirlwind,
          MOVES.firePunch,
          MOVES.fireBlast,
          MOVES.heatWave,
          MOVES.flamethrower,
          MOVES.fireSpin,
          MOVES.sunnyDay,
          MOVES.aquaTail,
          MOVES.dive,
          MOVES.waterfall,
          MOVES.aquaJet,
          MOVES.hydroPump,
          MOVES.surf,
          MOVES.waterPulse,
          MOVES.chillingWater,
          MOVES.rainDance,
          MOVES.thunderPunch,
          MOVES.thunder,
          MOVES.thunderbolt,
          MOVES.thunderWave,
          MOVES.fly,
          MOVES.aerialAce,
          MOVES.hurricane,
          MOVES.airSlash,
          MOVES.airCutter,
          MOVES.tailwind,
          MOVES.roost,
          MOVES.stoneEdge,
          MOVES.rockSlide,
          MOVES.rockTomb,
          MOVES.sandstorm,
          MOVES.earthquake,
          MOVES.stompingTantrum,
          MOVES.bulldoze,
          MOVES.iceSpinner,
          MOVES.icePunch,
          MOVES.blizzard,
          MOVES.iceBeam,
          MOVES.icyWind,
          MOVES.snowscape,
          MOVES.haze,
          MOVES.focusPunch,
          MOVES.superPower,
          MOVES.bodyPress,
          MOVES.brickBreak,
          MOVES.lowKick,
          MOVES.focusBlast,
          MOVES.rest,
          MOVES.lightScreen,
          MOVES.agility,
          MOVES.outrage,
          MOVES.dragonRush,
          MOVES.dragonClaw,
          MOVES.breakingSwipe,
          MOVES.dragonTail,
          MOVES.scaleShot,
          MOVES.dracoMeteor,
          MOVES.dragonPulse,
          MOVES.dragonCheer,
          MOVES.dragonDance,
          MOVES.brutalSwing,
          MOVES.fling,
          MOVES.ironTail,
          MOVES.ironHead,
          MOVES.steelWing,
        ],
      }
    },
  },
  154: {
    dexNumber: 154,
    dexName: "Meganium",
    forms: { [FORM_IDS.base]: null },
  },
  157: {
    dexNumber: 157,
    dexName: "Typhlosion",
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.hisuian]: null,
    },
  },
  160: {
    dexNumber: 160,
    dexName: "Feraligatr",
    forms: { [FORM_IDS.base]: null },
  },
  168: {
    dexNumber: 168,
    dexName: "Ariados",
    forms: { [FORM_IDS.base]: null },
  },
  181: {
    dexNumber: 181,
    dexName: "Ampharos",
    forms: {
      [FORM_IDS.base]: {
        hp: 165,
        attack: 95,
        defense: 105,
        spAtk: 135,
        spDef: 110,
        speed: 75,
        types: [TYPES.electric],
        moves: [
          MOVES.gigaImpact,
          MOVES.doubleEdge,
          MOVES.megaKick,
          MOVES.bodySlam,
          MOVES.facade,
          MOVES.endeavor,
          MOVES.hyperBeam,
          MOVES.round,
          MOVES.snore,
          MOVES.afterYou,
          MOVES.helpingHand,
          MOVES.safeguard,
          MOVES.sleepTalk,
          MOVES.endure,
          MOVES.protect,
          MOVES.substitue,
          MOVES.screech,
          MOVES.roar,
          MOVES.trailblaze,
          MOVES.cottonGuard,
          MOVES.cottonSpore,
          MOVES.firePunch,
          MOVES.sunnyDay,
          MOVES.rainDance,
          MOVES.supercellSlam,
          MOVES.wildCharge,
          MOVES.thunderPunch,
          MOVES.zapCannon,
          MOVES.thunder,
          MOVES.thunderbolt,
          MOVES.discharge,
          MOVES.risingVoltage,
          MOVES.voltSwitch,
          MOVES.parabolicCharge,
          MOVES.electroweb,
          MOVES.chargeBeam,
          MOVES.electroBall,
          MOVES.electricTerrain,
          MOVES.magneticFlux,
          MOVES.eerieImpulse,
          MOVES.charge,
          MOVES.thunderWave,
          MOVES.meteorBeam,
          MOVES.powerGem,
          MOVES.dig,
          MOVES.stompingTantrum,
          MOVES.bulldoze,
          MOVES.icePunch,
          MOVES.focusPunch,
          MOVES.brickBreak,
          MOVES.lowKick,
          MOVES.focusBlast,
          MOVES.rest,
          MOVES.reflect,
          MOVES.lightScreen,
          MOVES.agility,
          MOVES.confuseRay,
          MOVES.outrage,
          MOVES.breakingSwipe,
          MOVES.dragonTail,
          MOVES.dragonPulse,
          MOVES.dragonCheer,
          MOVES.brutalSwing,
          MOVES.fling,
          MOVES.flatter,
          MOVES.ironTail,
          MOVES.dazzlingGleam,
        ],
      }
    },
  },
  184: {
    dexNumber: 184,
    dexName: "Azumarill",
    forms: { [FORM_IDS.base]: null },
  },
  186: {
    dexNumber: 186,
    dexName: "Politoed",
    forms: { [FORM_IDS.base]: null },
  },
  196: {
    dexNumber: 196,
    dexName: "Espeon",
    forms: { [FORM_IDS.base]: null },
  },
  197: {
    dexNumber: 197,
    dexName: "Umbreon",
    forms: { [FORM_IDS.base]: null },
  },
  199: {
    dexNumber: 199,
    dexName: "Slowking",
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.galarian]: null,
    },
  },
  205: {
    dexNumber: 205,
    dexName: "Forretress",
    forms: { [FORM_IDS.base]: null },
  },
  208: {
    dexNumber: 208,
    dexName: "Steelix",
    forms: { [FORM_IDS.base]: null },
  },
  212: {
    dexNumber: 212,
    dexName: "Scizor",
    forms: { [FORM_IDS.base]: null },
  },
  214: {
    dexNumber: 214,
    dexName: "Heracross",
    forms: { [FORM_IDS.base]: null },
  },
  227: {
    dexNumber: 227,
    dexName: "Skarmory",
    forms: { [FORM_IDS.base]: null },
  },
  229: {
    dexNumber: 229,
    dexName: "Houndoom",
    forms: { [FORM_IDS.base]: null },
  },
  248: {
    dexNumber: 248,
    dexName: "Tyranitar",
    forms: { [FORM_IDS.base]: null },
  },
  279: {
    dexNumber: 279,
    dexName: "Pelipper",
    forms: { [FORM_IDS.base]: null },
  },
  282: {
    dexNumber: 282,
    dexName: "Gardevoir",
    forms: { [FORM_IDS.base]: null },
  },
  302: {
    dexNumber: 302,
    dexName: "Sableye",
    forms: { [FORM_IDS.base]: null },
  },
  306: {
    dexNumber: 306,
    dexName: "Aggron",
    forms: { [FORM_IDS.base]: null },
  },
  308: {
    dexNumber: 308,
    dexName: "Medicham",
    forms: { [FORM_IDS.base]: null },
  },
  310: {
    dexNumber: 310,
    dexName: "Manectric",
    forms: { [FORM_IDS.base]: null },
  },
  319: {
    dexNumber: 319,
    dexName: "Sharpedo",
    forms: { [FORM_IDS.base]: null },
  },
  323: {
    dexNumber: 323,
    dexName: "Camerupt",
    forms: { [FORM_IDS.base]: null },
  },
  324: {
    dexNumber: 324,
    dexName: "Torkoal",
    forms: { [FORM_IDS.base]: null },
  },
  334: {
    dexNumber: 334,
    dexName: "Altaria",
    forms: { [FORM_IDS.base]: null },
  },
  350: {
    dexNumber: 350,
    dexName: "Milotic",
    forms: { [FORM_IDS.base]: null },
  },
  351: {
    dexNumber: 351,
    dexName: "Castform",
    forms: { [FORM_IDS.base]: null },
  },
  354: {
    dexNumber: 354,
    dexName: "Banette",
    forms: { [FORM_IDS.base]: null },
  },
  358: {
    dexNumber: 358,
    dexName: "Chimecho",
    forms: { [FORM_IDS.base]: null },
  },
  359: {
    dexNumber: 359,
    dexName: "Absol",
    forms: { [FORM_IDS.base]: null },
  },
  362: {
    dexNumber: 362,
    dexName: "Glalie",
    forms: { [FORM_IDS.base]: null },
  },
  389: {
    dexNumber: 389,
    dexName: "Torterra",
    forms: { [FORM_IDS.base]: null },
  },
  392: {
    dexNumber: 392,
    dexName: "Infernape",
    forms: { [FORM_IDS.base]: null },
  },
  395: {
    dexNumber: 395,
    dexName: "Empoleon",
    forms: { [FORM_IDS.base]: null },
  },
  405: {
    dexNumber: 405,
    dexName: "Luxray",
    forms: { [FORM_IDS.base]: null },
  },
  407: {
    dexNumber: 407,
    dexName: "Roserade",
    forms: { [FORM_IDS.base]: null },
  },
  409: {
    dexNumber: 409,
    dexName: "Rampardos",
    forms: { [FORM_IDS.base]: null },
  },
  411: {
    dexNumber: 411,
    dexName: "Bastiodon",
    forms: { [FORM_IDS.base]: null },
  },
  428: {
    dexNumber: 428,
    dexName: "Lopunny",
    forms: { [FORM_IDS.base]: null },
  },
  442: {
    dexNumber: 442,
    dexName: "Spiritomb",
    forms: { [FORM_IDS.base]: null },
  },
  445: {
    dexNumber: 445,
    dexName: "Garchomp",
    forms: { [FORM_IDS.base]: null },
  },
  448: {
    dexNumber: 448,
    dexName: "Lucario",
    forms: { [FORM_IDS.base]: null },
  },
  450: {
    dexNumber: 450,
    dexName: "Hippowdon",
    forms: { [FORM_IDS.base]: null },
  },
  454: {
    dexNumber: 454,
    dexName: "Toxicroak",
    forms: { [FORM_IDS.base]: null },
  },
  460: {
    dexNumber: 460,
    dexName: "Abomasnow",
    forms: { [FORM_IDS.base]: null },
  },
  461: {
    dexNumber: 461,
    dexName: "Weavile",
    forms: { [FORM_IDS.base]: null },
  },
  464: {
    dexNumber: 464,
    dexName: "Rhyperior",
    forms: { [FORM_IDS.base]: null },
  },
  470: {
    dexNumber: 470,
    dexName: "Leafeon",
    forms: { [FORM_IDS.base]: null },
  },
  471: {
    dexNumber: 471,
    dexName: "Glaceon",
    forms: { [FORM_IDS.base]: null },
  },
  472: {
    dexNumber: 472,
    dexName: "Gliscor",
    forms: { [FORM_IDS.base]: null },
  },
  473: {
    dexNumber: 473,
    dexName: "Mamoswine",
    forms: { [FORM_IDS.base]: null },
  },
  475: {
    dexNumber: 475,
    dexName: "Gallade",
    forms: { [FORM_IDS.base]: null },
  },
  478: {
    dexNumber: 478,
    dexName: "Froslass",
    forms: { [FORM_IDS.base]: null },
  },
  479: {
    dexNumber: 479,
    dexName: "Rotom",
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.heat]: null,
      [FORM_IDS.wash]: null,
      [FORM_IDS.frost]: null,
      [FORM_IDS.fan]: null,
      [FORM_IDS.grass]: null,
    },
  },
  497: {
    dexNumber: 497,
    dexName: "Serperior",
    forms: { [FORM_IDS.base]: null },
  },
  500: {
    dexNumber: 500,
    dexName: "Emboar",
    forms: { [FORM_IDS.base]: null },
  },
  503: {
    dexNumber: 503,
    dexName: "Samurott",
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.hisuian]: null,
    },
  },
  505: {
    dexNumber: 505,
    dexName: "Watchog",
    forms: { [FORM_IDS.base]: null },
  },
  510: {
    dexNumber: 510,
    dexName: "Liepard",
    forms: { [FORM_IDS.base]: null },
  },
  512: {
    dexNumber: 512,
    dexName: "Simisage",
    forms: { [FORM_IDS.base]: null },
  },
  514: {
    dexNumber: 514,
    dexName: "Simisear",
    forms: { [FORM_IDS.base]: null },
  },
  516: {
    dexNumber: 516,
    dexName: "Simipour",
    forms: { [FORM_IDS.base]: null },
  },
  530: {
    dexNumber: 530,
    dexName: "Excadrill",
    forms: { [FORM_IDS.base]: null },
  },
  531: {
    dexNumber: 531,
    dexName: "Audino",
    forms: { [FORM_IDS.base]: null },
  },
  534: {
    dexNumber: 534,
    dexName: "Conkeldurr",
    forms: { [FORM_IDS.base]: null },
  },
  547: {
    dexNumber: 547,
    dexName: "Whimsicott",
    forms: {
      [FORM_IDS.base]: {
        hp: 135,
        attack: 87,
        defense: 105,
        spAtk: 97,
        spDef: 95,
        speed: 136,
        types: [TYPES.grass, TYPES.fairy],
        moves: [
          MOVES.gigaImpact,
          MOVES.facade,
          MOVES.endeavor,
          MOVES.hyperBeam,
          MOVES.round,
          MOVES.snore,
          MOVES.tickle,
          MOVES.helpingHand,
          MOVES.encore,
          MOVES.safeGuard,
          MOVES.sleepTalk,
          MOVES.attract,
          MOVES.endure,
          MOVES.protect,
          MOVES.substitue,
          MOVES.seedBomb,
          MOVES.grassyGlide,
          MOVES.solarBeam,
          MOVES.energyBall,
          MOVES.gigaDrain,
          MOVES.grassKnot,
          MOVES.grassyTerrain,
          MOVES.cottonGuard,
          MOVES.worrySeed,
          MOVES.cottonSpore,
          MOVES.stunSpore,
          MOVES.growth,
          MOVES.leechSeed,
          MOVES.sunnyDay,
          MOVES.uTurn,
          MOVES.hurricane,
          MOVES.tailwind,
          MOVES.poisonPowder,
          MOVES.psychic,
          MOVES.trickRoom,
          MOVES.rest,
          MOVES.lightScreen,
          MOVES.shadowBall,
          MOVES.thief,
          MOVES.fling,
          MOVES.beatUp,
          MOVES.switcheroo,
          MOVES.fakeTears,
          MOVES.taunt,
          MOVES.memento,
          MOVES.playRough,
          MOVES.moonblast,
          MOVES.dazzlingGleam,
          MOVES.mistyTerrain,
          MOVES.charm,
        ]
      }
    },
  },
  553: {
    dexNumber: 553,
    dexName: "Krookodile",
    forms: { [FORM_IDS.base]: null },
  },
  563: {
    dexNumber: 563,
    dexName: "Cofagrigus",
    forms: { [FORM_IDS.base]: null },
  },
  569: {
    dexNumber: 569,
    dexName: "Garbodor",
    forms: { [FORM_IDS.base]: null },
  },
  571: {
    dexNumber: 571,
    dexName: "Zoroark",
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.hisuian]: null,
    },
  },
  579: {
    dexNumber: 579,
    dexName: "Reuniclus",
    forms: { [FORM_IDS.base]: null },
  },
  584: {
    dexNumber: 584,
    dexName: "Vanilluxe",
    forms: { [FORM_IDS.base]: null },
  },
  587: {
    dexNumber: 587,
    dexName: "Emolga",
    forms: { [FORM_IDS.base]: null },
  },
  609: {
    dexNumber: 609,
    dexName: "Chandelure",
    forms: { [FORM_IDS.base]: null },
  },
  614: {
    dexNumber: 614,
    dexName: "Beartic",
    forms: { [FORM_IDS.base]: null },
  },
  618: {
    dexNumber: 618,
    dexName: "Stunfisk",
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.galarian]: null,
    },
  },
  623: {
    dexNumber: 623,
    dexName: "Golurk",
    forms: { [FORM_IDS.base]: null },
  },
  635: {
    dexNumber: 635,
    dexName: "Hydreigon",
    forms: { [FORM_IDS.base]: null },
  },
  637: {
    dexNumber: 637,
    dexName: "Volcarona",
    forms: { [FORM_IDS.base]: null },
  },
  652: {
    dexNumber: 652,
    dexName: "Chesnaught",
    forms: { [FORM_IDS.base]: null },
  },
  655: {
    dexNumber: 655,
    dexName: "Delphox",
    forms: { [FORM_IDS.base]: null },
  },
  658: {
    dexNumber: 658,
    dexName: "Greninja",
    forms: { [FORM_IDS.base]: null },
  },
  660: {
    dexNumber: 660,
    dexName: "Diggersby",
    forms: { [FORM_IDS.base]: null },
  },
  663: {
    dexNumber: 663,
    dexName: "Talonflame",
    forms: { [FORM_IDS.base]: null },
  },
  666: {
    dexNumber: 666,
    dexName: "Vivillon",
    forms: { [FORM_IDS.base]: null },
  },
  670: {
    dexNumber: 670,
    dexName: "Floette",
    forms: { [FORM_IDS.base]: null },
  },
  671: {
    dexNumber: 671,
    dexName: "Florges",
    forms: { [FORM_IDS.base]: null },
  },
  675: {
    dexNumber: 675,
    dexName: "Pangoro",
    forms: { [FORM_IDS.base]: null },
  },
  676: {
    dexNumber: 676,
    dexName: "Furfrou",
    forms: { [FORM_IDS.base]: null },
  },
  678: {
    dexNumber: 678,
    dexName: "Meowstic",
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.female]: null,
    },
  },
  681: {
    dexNumber: 681,
    dexName: "Aegislash",
    forms: { [FORM_IDS.base]: null },
  },
  683: {
    dexNumber: 683,
    dexName: "Aromatisse",
    forms: { [FORM_IDS.base]: null },
  },
  685: {
    dexNumber: 685,
    dexName: "Slurpuff",
    forms: { [FORM_IDS.base]: null },
  },
  693: {
    dexNumber: 693,
    dexName: "Clawitzer",
    forms: { [FORM_IDS.base]: null },
  },
  695: {
    dexNumber: 695,
    dexName: "Heliolisk",
    forms: { [FORM_IDS.base]: null },
  },
  697: {
    dexNumber: 697,
    dexName: "Tyrantrum",
    forms: { [FORM_IDS.base]: null },
  },
  699: {
    dexNumber: 699,
    dexName: "Aurorus",
    forms: { [FORM_IDS.base]: null },
  },
  700: {
    dexNumber: 700,
    dexName: "Sylveon",
    forms: {
      [FORM_IDS.base]: {
        hp: 170,
        attack: 85,
        defense: 85,
        spAtk: 130,
        spDef: 150,
        speed: 80,
        types: [TYPES.fairy],
        moves: [
          MOVES.gigaImpact,
          MOVES.lastResort,
          MOVES.doubleEdge,
          MOVES.bodySlam,
          MOVES.facade,
          MOVES.covet,
          MOVES.quickAttack,
          MOVES.flail,
          MOVES.hyperBeam,
          MOVES.hyperVoice,
          MOVES.round,
          MOVES.weatherBall,
          MOVES.snore,
          MOVES.copycat,
          MOVES.tickle,
          MOVES.yawn,
          MOVES.wish,
          MOVES.helpingHand,
          MOVES.psychUp,
          MOVES.batonPass,
          MOVES.safeguard,
          MOVES.sleepTalk,
          MOVES.endure,
          MOVES.protect,
          MOVES.substitue,
          MOVES.focusEnergy,
          MOVES.roar,
          MOVES.trailblaze,
          MOVES.mysticalFire,
          MOVES.sunnyDay,
          MOVES.rainDance,
          MOVES.dig,
          MOVES.mudSlap,
          MOVES.detect,
          MOVES.psychic,
          MOVES.psyshock,
          MOVES.storedPower,
          MOVES.calmMind,
          MOVES.skillSwap,
          MOVES.rest,
          MOVES.reflect,
          MOVES.lightScreen,
          MOVES.shadowBall,
          MOVES.curse,
          MOVES.bite,
          MOVES.fakeTears,
          MOVES.playRough,
          MOVES.mistyExplosion,
          MOVES.moonblast,
          MOVES.alluringVoice,
          MOVES.dazzlingGleam,
          MOVES.drainingKiss,
          MOVES.babyDollEyes,
          MOVES.mistyTerrain,
          MOVES.charm,
        ],
      }
    },
  },
  701: {
    dexNumber: 701,
    dexName: "Hawlucha",
    forms: { [FORM_IDS.base]: null },
  },
  702: {
    dexNumber: 702,
    dexName: "Dedenne",
    forms: { [FORM_IDS.base]: null },
  },
  706: {
    dexNumber: 706,
    dexName: "Goodra",
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.hisuian]: null,
    },
  },
  707: {
    dexNumber: 707,
    dexName: "Klefki",
    forms: { [FORM_IDS.base]: null },
  },
  709: {
    dexNumber: 709,
    dexName: "Trevenant",
    forms: { [FORM_IDS.base]: null },
  },
  711: {
    dexNumber: 711,
    dexName: "Gourgeist",
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.medium]: null,
      [FORM_IDS.small]: null,
      [FORM_IDS.large]: null,
      [FORM_IDS.jumbo]: null,
    },
  },
  713: {
    dexNumber: 713,
    dexName: "Avalugg",
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.hisuian]: null,
    },
  },
  715: {
    dexNumber: 715,
    dexName: "Noivern",
    forms: { [FORM_IDS.base]: null },
  },
  724: {
    dexNumber: 724,
    dexName: "Decidueye",
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.hisuian]: null,
    },
  },
  727: {
    dexNumber: 727,
    dexName: "Incineroar",
    forms: { [FORM_IDS.base]: null },
  },
  730: {
    dexNumber: 730,
    dexName: "Primarina",
    forms: { [FORM_IDS.base]: null },
  },
  733: {
    dexNumber: 733,
    dexName: "Toucannon",
    forms: { [FORM_IDS.base]: null },
  },
  740: {
    dexNumber: 740,
    dexName: "Crabominable",
    forms: { [FORM_IDS.base]: null },
  },
  745: {
    dexNumber: 745,
    dexName: "Lycanroc",
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.midnight]: null,
      [FORM_IDS.dusk]: null,
    },
  },
  748: {
    dexNumber: 748,
    dexName: "Toxapex",
    forms: { [FORM_IDS.base]: null },
  },
  750: {
    dexNumber: 750,
    dexName: "Mudsdale",
    forms: { [FORM_IDS.base]: null },
  },
  752: {
    dexNumber: 752,
    dexName: "Araquanid",
    forms: { [FORM_IDS.base]: null },
  },
  758: {
    dexNumber: 758,
    dexName: "Salazzle",
    forms: { [FORM_IDS.base]: null },
  },
  763: {
    dexNumber: 763,
    dexName: "Tsareena",
    forms: { [FORM_IDS.base]: null },
  },
  765: {
    dexNumber: 765,
    dexName: "Oranguru",
    forms: { [FORM_IDS.base]: null },
  },
  766: {
    dexNumber: 766,
    dexName: "Passimian",
    forms: { [FORM_IDS.base]: null },
  },
  778: {
    dexNumber: 778,
    dexName: "Mimikyu",
    forms: { [FORM_IDS.base]: null },
  },
  780: {
    dexNumber: 780,
    dexName: "Drampa",
    forms: { [FORM_IDS.base]: null },
  },
  784: {
    dexNumber: 784,
    dexName: "Kommo O",
    forms: { [FORM_IDS.base]: null },
  },
  823: {
    dexNumber: 823,
    dexName: "Corviknight",
    forms: { [FORM_IDS.base]: null },
  },
  841: {
    dexNumber: 841,
    dexName: "Flapple",
    forms: { [FORM_IDS.base]: null },
  },
  842: {
    dexNumber: 842,
    dexName: "Appletun",
    forms: { [FORM_IDS.base]: null },
  },
  844: {
    dexNumber: 844,
    dexName: "Sandaconda",
    forms: { [FORM_IDS.base]: null },
  },
  855: {
    dexNumber: 855,
    dexName: "Polteageist",
    forms: { [FORM_IDS.base]: null },
  },
  858: {
    dexNumber: 858,
    dexName: "Hatterene",
    forms: { [FORM_IDS.base]: null },
  },
  866: {
    dexNumber: 866,
    dexName: "Mr Rime",
    forms: { [FORM_IDS.base]: null },
  },
  867: {
    dexNumber: 867,
    dexName: "Runerigus",
    forms: { [FORM_IDS.base]: null },
  },
  869: {
    dexNumber: 869,
    dexName: "Alcremie",
    forms: { [FORM_IDS.base]: null },
  },
  877: {
    dexNumber: 877,
    dexName: "Morpeko",
    forms: { [FORM_IDS.base]: null },
  },
  887: {
    dexNumber: 887,
    dexName: "Dragapult",
    forms: { [FORM_IDS.base]: null },
  },
  899: {
    dexNumber: 899,
    dexName: "Wyrdeer",
    forms: { [FORM_IDS.base]: null },
  },
  900: {
    dexNumber: 900,
    dexName: "Kleavor",
    forms: { [FORM_IDS.base]: null },
  },
  902: {
    dexNumber: 902,
    dexName: "Basculegion",
    forms: {
      [FORM_IDS.base]: null,
      [FORM_IDS.female]: null,
    },
  },
  903: {
    dexNumber: 903,
    dexName: "Sneasler",
    forms: { [FORM_IDS.base]: null },
  },
  908: {
    dexNumber: 908,
    dexName: "Meowscarada",
    forms: { [FORM_IDS.base]: null },
  },
  911: {
    dexNumber: 911,
    dexName: "Skeledirge",
    forms: { [FORM_IDS.base]: null },
  },
  914: {
    dexNumber: 914,
    dexName: "Quaquaval",
    forms: { [FORM_IDS.base]: null },
  },
  925: {
    dexNumber: 925,
    dexName: "Maushold",
    forms: { [FORM_IDS.base]: null },
  },
  934: {
    dexNumber: 934,
    dexName: "Garganacl",
    forms: { [FORM_IDS.base]: null },
  },
  936: {
    dexNumber: 936,
    dexName: "Armarouge",
    forms: { [FORM_IDS.base]: null },
  },
  937: {
    dexNumber: 937,
    dexName: "Ceruledge",
    forms: {
      [FORM_IDS.base]: {
        hp: 150,
        attack: 145,
        defense: 100,
        spAtk: 80,
        spDef: 120,
        speed: 105,
        types: [TYPES.fire, TYPES.ghost],
        moves: [
          MOVES.gigaImpact,
          MOVES.facade,
          MOVES.helpingHand,
          MOVES.psychUp,
          MOVES.sleepTalk,
          MOVES.endure,
          MOVES.protect,
          MOVES.substitue,
          MOVES.disable,
          MOVES.swordsDance,
          MOVES.solarBlade,
          MOVES.flareBlitz,
          MOVES.bitterBlade,
          MOVES.flameCharge,
          MOVES.burnUp,
          MOVES.overheat,
          MOVES.fireBlast,
          MOVES.heatWave,
          MOVES.flamethrower,
          MOVES.lavaPlume,
          MOVES.fireSpin,
          MOVES.willOWisp,
          MOVES.sunnyDay,
          MOVES.xScissor,
          MOVES.poisonJab,
          MOVES.clearSmog,
          MOVES.closeCombat,
          MOVES.brickBreak,
          MOVES.vacuumWave,
          MOVES.quickGuard,
          MOVES.bulkUp,
          MOVES.psychoCut,
          MOVES.storedPower,
          MOVES.allySwitch,
          MOVES.rest,
          MOVES.reflect,
          MOVES.lightScreen,
          MOVES.poltergeist,
          MOVES.phantomForce,
          MOVES.shadowClaw,
          MOVES.shadowSneak,
          MOVES.shadowBall,
          MOVES.hex,
          MOVES.nightShade,
          MOVES.destinyBond,
          MOVES.spite,
          MOVES.curse,
          MOVES.confuseRay,
          MOVES.dragonClaw,
          MOVES.throatChop,
          MOVES.nightSlash,
          MOVES.fling,
          MOVES.taunt,
          MOVES.ironHead,
          MOVES.ironDefense,
        ],
      },
    },
  },
  939: {
    dexNumber: 939,
    dexName: "Bellibolt",
    forms: { [FORM_IDS.base]: null },
  },
  952: {
    dexNumber: 952,
    dexName: "Scovillain",
    forms: { [FORM_IDS.base]: null },
  },
  956: {
    dexNumber: 956,
    dexName: "Espathra",
    forms: { [FORM_IDS.base]: null },
  },
  959: {
    dexNumber: 959,
    dexName: "Tinkaton",
    forms: { [FORM_IDS.base]: null },
  },
  964: {
    dexNumber: 964,
    dexName: "Palafin",
    forms: { [FORM_IDS.base]: null },
  },
  968: {
    dexNumber: 968,
    dexName: "Orthworm",
    forms: { [FORM_IDS.base]: null },
  },
  970: {
    dexNumber: 970,
    dexName: "Glimmora",
    forms: { [FORM_IDS.base]: null },
  },
  981: {
    dexNumber: 981,
    dexName: "Farigiraf",
    forms: { [FORM_IDS.base]: null },
  },
  983: {
    dexNumber: 983,
    dexName: "Kingambit",
    forms: { [FORM_IDS.base]: null },
  },
  1013: {
    dexNumber: 1013,
    dexName: "Sinistcha",
    forms: { [FORM_IDS.base]: null },
  },
  1018: {
    dexNumber: 1018,
    dexName: "Archaludon",
    forms: { [FORM_IDS.base]: null },
  },
  1019: {
    dexNumber: 1019,
    dexName: "Hydrapple",
    forms: { [FORM_IDS.base]: null },
  },
};

export function getDexIds(): number[] {
  return Object.keys(dexObject)
    .map((k) => Number(k))
    .filter((n) => Number.isFinite(n))
    .sort((a, b) => a - b);
}

