/** Canonical type name strings — use these instead of raw `"dragon"` literals. */
export const TYPE_NAMES = {
  bug: "bug",
  dark: "dark",
  dragon: "dragon",
  electric: "electric",
  fairy: "fairy",
  fighting: "fighting",
  fire: "fire",
  flying: "flying",
  ghost: "ghost",
  grass: "grass",
  ground: "ground",
  ice: "ice",
  normal: "normal",
  poison: "poison",
  psychic: "psychic",
  rock: "rock",
  steel: "steel",
  water: "water",
} as const;

export type TypeName = (typeof TYPE_NAMES)[keyof typeof TYPE_NAMES];


export type TypeModifierTable = Partial<Record<TypeName, number>>;

export type TypeRecord = {
  typeName: TypeName;
  typeAtkModifier: TypeModifierTable;
  typeDefModifier: TypeModifierTable;
};

export const TYPES = {
  bug: {
    typeName: TYPE_NAMES.bug,
    typeAtkModifier: {
      [TYPE_NAMES.bug]: 1,
      [TYPE_NAMES.dark]: 2,
      [TYPE_NAMES.dragon]: 1,
      [TYPE_NAMES.electric]: 1,
      [TYPE_NAMES.fairy]: 0.5,
      [TYPE_NAMES.fighting]: 0.5,
      [TYPE_NAMES.fire]: 0.5,
      [TYPE_NAMES.flying]: 0.5,
      [TYPE_NAMES.ghost]: 0.5,
      [TYPE_NAMES.grass]: 2,
      [TYPE_NAMES.ground]: 1,
      [TYPE_NAMES.ice]: 1,
      [TYPE_NAMES.normal]: 1,
      [TYPE_NAMES.poison]: 0.5,
      [TYPE_NAMES.psychic]: 2,
      [TYPE_NAMES.rock]: 1,
      [TYPE_NAMES.steel]: 0.5,
      [TYPE_NAMES.water]: 1,
    },
    typeDefModifier: {
      [TYPE_NAMES.bug]: 1,
      [TYPE_NAMES.dark]: 1,
      [TYPE_NAMES.dragon]: 1,
      [TYPE_NAMES.electric]: 1,
      [TYPE_NAMES.fairy]: 1,
      [TYPE_NAMES.fighting]: 0.5,
      [TYPE_NAMES.fire]: 2,
      [TYPE_NAMES.flying]: 2,
      [TYPE_NAMES.ghost]: 1,
      [TYPE_NAMES.grass]: 0.5,
      [TYPE_NAMES.ground]: 0.5,
      [TYPE_NAMES.ice]: 1,
      [TYPE_NAMES.normal]: 1,
      [TYPE_NAMES.poison]: 1,
      [TYPE_NAMES.psychic]: 1,
      [TYPE_NAMES.rock]: 2,
      [TYPE_NAMES.steel]: 1,
      [TYPE_NAMES.water]: 1,
    },
  },
  dark: {
    typeName: TYPE_NAMES.dark,
    typeAtkModifier: {
      [TYPE_NAMES.bug]: 1,
      [TYPE_NAMES.dark]: 0.5,
      [TYPE_NAMES.dragon]: 1,
      [TYPE_NAMES.electric]: 1,
      [TYPE_NAMES.fairy]: 0.5,
      [TYPE_NAMES.fighting]: 0.5,
      [TYPE_NAMES.fire]: 1,
      [TYPE_NAMES.flying]: 1,
      [TYPE_NAMES.ghost]: 2,
      [TYPE_NAMES.grass]: 1,
      [TYPE_NAMES.ground]: 1,
      [TYPE_NAMES.ice]: 1,
      [TYPE_NAMES.normal]: 1,
      [TYPE_NAMES.poison]: 1,
      [TYPE_NAMES.psychic]: 2,
      [TYPE_NAMES.rock]: 1,
      [TYPE_NAMES.steel]: 1,
      [TYPE_NAMES.water]: 1,
    },
    typeDefModifier: {
      [TYPE_NAMES.bug]: 2,
      [TYPE_NAMES.dark]: 0.5,
      [TYPE_NAMES.dragon]: 1,
      [TYPE_NAMES.electric]: 1,
      [TYPE_NAMES.fairy]: 2,
      [TYPE_NAMES.fighting]: 2,
      [TYPE_NAMES.fire]: 1,
      [TYPE_NAMES.flying]: 1,
      [TYPE_NAMES.ghost]: 0.5,
      [TYPE_NAMES.grass]: 1,
      [TYPE_NAMES.ground]: 1,
      [TYPE_NAMES.ice]: 1,
      [TYPE_NAMES.normal]: 1,
      [TYPE_NAMES.poison]: 1,
      [TYPE_NAMES.psychic]: 0,
      [TYPE_NAMES.rock]: 1,
      [TYPE_NAMES.steel]: 1,
      [TYPE_NAMES.water]: 1,
    },
  },
  dragon: {
    typeName: TYPE_NAMES.dragon,
    typeAtkModifier: {
      [TYPE_NAMES.bug]: 1,
      [TYPE_NAMES.dark]: 1,
      [TYPE_NAMES.dragon]: 2,
      [TYPE_NAMES.electric]: 1,
      [TYPE_NAMES.fairy]: 0,
      [TYPE_NAMES.fighting]: 1,
      [TYPE_NAMES.fire]: 1,
      [TYPE_NAMES.flying]: 1,
      [TYPE_NAMES.ghost]: 1,
      [TYPE_NAMES.grass]: 1,
      [TYPE_NAMES.ground]: 1,
      [TYPE_NAMES.ice]: 1,
      [TYPE_NAMES.normal]: 1,
      [TYPE_NAMES.poison]: 1,
      [TYPE_NAMES.psychic]: 1,
      [TYPE_NAMES.rock]: 1,
      [TYPE_NAMES.steel]: 0.5,
      [TYPE_NAMES.water]: 1,
    },
    typeDefModifier: {
      [TYPE_NAMES.bug]: 1,
      [TYPE_NAMES.dark]: 1,
      [TYPE_NAMES.dragon]: 2,
      [TYPE_NAMES.electric]: 0.5,
      [TYPE_NAMES.fairy]: 2,
      [TYPE_NAMES.fighting]: 1,
      [TYPE_NAMES.fire]: 0.5,
      [TYPE_NAMES.flying]: 1,
      [TYPE_NAMES.ghost]: 1,
      [TYPE_NAMES.grass]: 0.5,
      [TYPE_NAMES.ground]: 1,
      [TYPE_NAMES.ice]: 2,
      [TYPE_NAMES.normal]: 1,
      [TYPE_NAMES.poison]: 1,
      [TYPE_NAMES.psychic]: 1,
      [TYPE_NAMES.rock]: 1,
      [TYPE_NAMES.steel]: 1,
      [TYPE_NAMES.water]: 0.5,
    },
  },
  electric: {
    typeName: TYPE_NAMES.electric,
    typeAtkModifier: {
      [TYPE_NAMES.bug]: 1,
      [TYPE_NAMES.dark]: 1,
      [TYPE_NAMES.dragon]: 0.5,
      [TYPE_NAMES.electric]: 0.5,
      [TYPE_NAMES.fairy]: 1,
      [TYPE_NAMES.fighting]: 1,
      [TYPE_NAMES.fire]: 1,
      [TYPE_NAMES.flying]: 2,
      [TYPE_NAMES.ghost]: 1,
      [TYPE_NAMES.grass]: 0.5,
      [TYPE_NAMES.ground]: 0,
      [TYPE_NAMES.ice]: 1,
      [TYPE_NAMES.normal]: 1,
      [TYPE_NAMES.poison]: 1,
      [TYPE_NAMES.psychic]: 1,
      [TYPE_NAMES.rock]: 1,
      [TYPE_NAMES.steel]: 1,
      [TYPE_NAMES.water]: 2,
    },
    typeDefModifier: {
      [TYPE_NAMES.bug]: 1,
      [TYPE_NAMES.dark]: 1,
      [TYPE_NAMES.dragon]: 1,
      [TYPE_NAMES.electric]: 0.5,
      [TYPE_NAMES.fairy]: 1,
      [TYPE_NAMES.fighting]: 1,
      [TYPE_NAMES.fire]: 1,
      [TYPE_NAMES.flying]: 0.5,
      [TYPE_NAMES.ghost]: 1,
      [TYPE_NAMES.grass]: 1,
      [TYPE_NAMES.ground]: 2,
      [TYPE_NAMES.ice]: 1,
      [TYPE_NAMES.normal]: 1,
      [TYPE_NAMES.poison]: 1,
      [TYPE_NAMES.psychic]: 1,
      [TYPE_NAMES.rock]: 1,
      [TYPE_NAMES.steel]: 0.5,
      [TYPE_NAMES.water]: 1,
    },
  },
  fairy: {
    typeName: TYPE_NAMES.fairy,
    typeAtkModifier: {
      [TYPE_NAMES.bug]: 1,
      [TYPE_NAMES.dark]: 2,
      [TYPE_NAMES.dragon]: 2,
      [TYPE_NAMES.electric]: 1,
      [TYPE_NAMES.fairy]: 1,
      [TYPE_NAMES.fighting]: 2,
      [TYPE_NAMES.fire]: 0.5,
      [TYPE_NAMES.flying]: 1,
      [TYPE_NAMES.ghost]: 1,
      [TYPE_NAMES.grass]: 1,
      [TYPE_NAMES.ground]: 1,
      [TYPE_NAMES.ice]: 1,
      [TYPE_NAMES.normal]: 1,
      [TYPE_NAMES.poison]: 0.5,
      [TYPE_NAMES.psychic]: 1,
      [TYPE_NAMES.rock]: 1,
      [TYPE_NAMES.steel]: 0.5,
      [TYPE_NAMES.water]: 1,
    },
    typeDefModifier: {
      [TYPE_NAMES.bug]: 0.5,
      [TYPE_NAMES.dark]: 0.5,
      [TYPE_NAMES.dragon]: 0,
      [TYPE_NAMES.electric]: 1,
      [TYPE_NAMES.fairy]: 1,
      [TYPE_NAMES.fighting]: 0.5,
      [TYPE_NAMES.fire]: 1,
      [TYPE_NAMES.flying]: 1,
      [TYPE_NAMES.ghost]: 1,
      [TYPE_NAMES.grass]: 1,
      [TYPE_NAMES.ground]: 1,
      [TYPE_NAMES.ice]: 1,
      [TYPE_NAMES.normal]: 1,
      [TYPE_NAMES.poison]: 2,
      [TYPE_NAMES.psychic]: 1,
      [TYPE_NAMES.rock]: 1,
      [TYPE_NAMES.steel]: 2,
      [TYPE_NAMES.water]: 1,
    },
  },
  fighting: {
    typeName: TYPE_NAMES.fighting,
    typeAtkModifier: {
      [TYPE_NAMES.bug]: 0.5,
      [TYPE_NAMES.dark]: 2,
      [TYPE_NAMES.dragon]: 1,
      [TYPE_NAMES.electric]: 1,
      [TYPE_NAMES.fairy]: 0.5,
      [TYPE_NAMES.fighting]: 1,
      [TYPE_NAMES.fire]: 1,
      [TYPE_NAMES.flying]: 0.5,
      [TYPE_NAMES.ghost]: 0,
      [TYPE_NAMES.grass]: 1,
      [TYPE_NAMES.ground]: 1,
      [TYPE_NAMES.ice]: 2,
      [TYPE_NAMES.normal]: 2,
      [TYPE_NAMES.poison]: 0.5,
      [TYPE_NAMES.psychic]: 0.5,
      [TYPE_NAMES.rock]: 2,
      [TYPE_NAMES.steel]: 2,
      [TYPE_NAMES.water]: 1,
    },
    typeDefModifier: {
      [TYPE_NAMES.bug]: 0.5,
      [TYPE_NAMES.dark]: 0.5,
      [TYPE_NAMES.dragon]: 1,
      [TYPE_NAMES.electric]: 1,
      [TYPE_NAMES.fairy]: 2,
      [TYPE_NAMES.fighting]: 1,
      [TYPE_NAMES.fire]: 1,
      [TYPE_NAMES.flying]: 2,
      [TYPE_NAMES.ghost]: 1,
      [TYPE_NAMES.grass]: 1,
      [TYPE_NAMES.ground]: 1,
      [TYPE_NAMES.ice]: 1,
      [TYPE_NAMES.normal]: 1,
      [TYPE_NAMES.poison]: 1,
      [TYPE_NAMES.psychic]: 2,
      [TYPE_NAMES.rock]: 0.5,
      [TYPE_NAMES.steel]: 1,
      [TYPE_NAMES.water]: 1,
    },
  },
  fire: {
    typeName: TYPE_NAMES.fire,
    typeAtkModifier: {
      [TYPE_NAMES.bug]: 2,
      [TYPE_NAMES.dark]: 1,
      [TYPE_NAMES.dragon]: 0.5,
      [TYPE_NAMES.electric]: 1,
      [TYPE_NAMES.fairy]: 1,
      [TYPE_NAMES.fighting]: 1,
      [TYPE_NAMES.fire]: 0.5,
      [TYPE_NAMES.flying]: 1,
      [TYPE_NAMES.ghost]: 1,
      [TYPE_NAMES.grass]: 2,
      [TYPE_NAMES.ground]: 1,
      [TYPE_NAMES.ice]: 2,
      [TYPE_NAMES.normal]: 1,
      [TYPE_NAMES.poison]: 1,
      [TYPE_NAMES.psychic]: 1,
      [TYPE_NAMES.rock]: 0.5,
      [TYPE_NAMES.steel]: 2,
      [TYPE_NAMES.water]: 0.5,
    },
    typeDefModifier: {
      [TYPE_NAMES.bug]: 0.5,
      [TYPE_NAMES.dark]: 1,
      [TYPE_NAMES.dragon]: 1,
      [TYPE_NAMES.electric]: 1,
      [TYPE_NAMES.fairy]: 0.5,
      [TYPE_NAMES.fighting]: 1,
      [TYPE_NAMES.fire]: 0.5,
      [TYPE_NAMES.flying]: 1,
      [TYPE_NAMES.ghost]: 1,
      [TYPE_NAMES.grass]: 0.5,
      [TYPE_NAMES.ground]: 2,
      [TYPE_NAMES.ice]: 0.5,
      [TYPE_NAMES.normal]: 1,
      [TYPE_NAMES.poison]: 1,
      [TYPE_NAMES.psychic]: 1,
      [TYPE_NAMES.rock]: 2,
      [TYPE_NAMES.steel]: 0.5,
      [TYPE_NAMES.water]: 2,
    },
  },
  flying: {
    typeName: TYPE_NAMES.flying,
    typeAtkModifier: {
      [TYPE_NAMES.bug]: 2,
      [TYPE_NAMES.dark]: 1,
      [TYPE_NAMES.dragon]: 1,
      [TYPE_NAMES.electric]: 0.5,
      [TYPE_NAMES.fairy]: 1,
      [TYPE_NAMES.fighting]: 2,
      [TYPE_NAMES.fire]: 1,
      [TYPE_NAMES.flying]: 1,
      [TYPE_NAMES.ghost]: 1,
      [TYPE_NAMES.grass]: 2,
      [TYPE_NAMES.ground]: 1,
      [TYPE_NAMES.ice]: 1,
      [TYPE_NAMES.normal]: 1,
      [TYPE_NAMES.poison]: 1,
      [TYPE_NAMES.psychic]: 1,
      [TYPE_NAMES.rock]: 0.5,
      [TYPE_NAMES.steel]: 0.5,
      [TYPE_NAMES.water]: 1,
    },
    typeDefModifier: {
      [TYPE_NAMES.bug]: 0.5,
      [TYPE_NAMES.dark]: 1,
      [TYPE_NAMES.dragon]: 1,
      [TYPE_NAMES.electric]: 2,
      [TYPE_NAMES.fairy]: 1,
      [TYPE_NAMES.fighting]: 0.5,
      [TYPE_NAMES.fire]: 1,
      [TYPE_NAMES.flying]: 1,
      [TYPE_NAMES.ghost]: 1,
      [TYPE_NAMES.grass]: 0.5,
      [TYPE_NAMES.ground]: 0,
      [TYPE_NAMES.ice]: 2,
      [TYPE_NAMES.normal]: 1,
      [TYPE_NAMES.poison]: 1,
      [TYPE_NAMES.psychic]: 1,
      [TYPE_NAMES.rock]: 2,
      [TYPE_NAMES.steel]: 1,
      [TYPE_NAMES.water]: 1,
    },
  },
  ghost: {
    typeName: TYPE_NAMES.ghost,
    typeAtkModifier: {},
    typeDefModifier: {},
  },
  grass: {
    typeName: TYPE_NAMES.grass,
    typeAtkModifier: {},
    typeDefModifier: {},
  },
  ground: {
    typeName: TYPE_NAMES.ground,
    typeAtkModifier: {},
    typeDefModifier: {},
  },
  ice: {
    typeName: TYPE_NAMES.ice,
    typeAtkModifier: {},
    typeDefModifier: {},
  },
  normal: {
    typeName: TYPE_NAMES.normal,
    typeAtkModifier: {},
    typeDefModifier: {},
  },
  poison: {
    typeName: TYPE_NAMES.poison,
    typeAtkModifier: {},
    typeDefModifier: {},
  },
  psychic: {
    typeName: TYPE_NAMES.psychic,
    typeAtkModifier: {},
    typeDefModifier: {},
  },
  rock: {
    typeName: TYPE_NAMES.rock,
    typeAtkModifier: {},
    typeDefModifier: {},
  },
  steel: {
    typeName: TYPE_NAMES.steel,
    typeAtkModifier: {},
    typeDefModifier: {},
  },
  water: {
    typeName: TYPE_NAMES.water,
    typeAtkModifier: {},
    typeDefModifier: {},
  },
} as const satisfies Record<string, TypeRecord>;

export type TypeId = (typeof TYPES)[keyof typeof TYPES];
